### ISSUE TITLE
can't delete test pending payments from the "All Payment Entries" list

### ISSUE THREAD

**Issue by Slashangel** [fluentform/fluentform#107]
I don't know how, but if I select one or all "charges" it appear "bulk actions", if I select "delete permanently" and apply they are all still there :(

**Comment by alex-authlab** [comment]
Thanks for reporting, we will fix the issue before the next update.

**Comment by alex-authlab** [comment]
Hello @Slashangel ,
You can just delete the entries from the payment form entries, then the associated payment entry will also be deleted. The delete option from the payment entry page is not needed now, we will remove it.
Thanks

**Comment by Slashangel** [comment]
Please don't do that because I have at least 15 different forms in a single website and having all the entries in a single page is a huge time saving, especially if I need to delete many and many of them going into every single form.

**Comment by alex-authlab** [comment]
I understand we will discuss this with our team, for your information, you can now bulk delete entries that will also delete associated payments.

**Comment by alex-authlab** [comment]
This issue was fixed
