### ISSUE TITLE
Feature Request - Export Entries of Form on a schedule to a particular email address.

### ISSUE THREAD

**Issue by neural-oD** [fluentform/fluentform#109]
Hi, 

I would like to suggest a feature to the system. It would be great if we could schedule exports of the form entries / results to different email addresses, at specified times or schedules.
Love your sofware, but this would really enhance. 
At the moment, we also have a pro version of wpallimport and export. They have a section which allows others to use their API's....have a look here: [Link](https://www.wpallimport.com/documentation/addon-dev/overview/)

Gravity forms is already supported. Love your forms way better. Would it be possible, to see if you could do something with their API on your end? I'm sure many form users would be happy with this.

Thanks so much

ps - I did post this in the support ticket area, but not sure if you guys handled those.

Any other suggestions for getting this working?

**Comment by alex-authlab** [comment]
Hello there,
Thank you for reaching to us here again. We have added this as a feature request in our internal board. Our Dev team will soon look into this. It really seems like a nice feature.
Thanks
