### ISSUE TITLE
Mouse text click or selection isn't working on choice fields with Firefox

### ISSUE THREAD

**Issue by yankiara** [fluentform/fluentform#11]
Hi,

When editing Dropdown/Radio/Checkbox/Multiple choice options list, mouse click or selection doesn't work on option fields with Firefox:
- no click in the middle of the text;
- no selection by dragging pointer;
- no selection with double click.

We can just click in the field text area to get focus.

Everything is OK with Chrome, though.

![Screenshot_2](https://user-images.githubusercontent.com/36680757/67073174-c08eb380-f186-11e9-8096-66037b696401.png)

**Comment by nkb-bd** [comment]
Thanks for reporting we will look into the issue.
