### ISSUE TITLE
WP CLI - integration?  #enhancement

### ISSUE THREAD

**Issue by neural-oD** [fluentform/fluentform#110]
Hi Guys,

I use wp-cli extensively. Is there a roadmap, or are you planning to support wp-cli any time soon?

Thanks

**Comment by techjewel** [comment]
Hello @neural-oD 
What type of commands you would like to see on Fluent Forms?

**Comment by neural-oD** [comment]
Hi @techjewel 

For me the most important feature on this would be to be able to export the entries of a particular form.
For example, I might want to do a csv dump of all entries of a particular form. With wp-cli, I could then script this to send scheduled reports to an email or whatever I wish.
This would be an awesome feature if you could enable wp-cli capabilites.

**Comment by nkb-bd** [comment]
Thanks, We will add this to our feature request.
