### ISSUE TITLE
PDF functional Error

### ISSUE THREAD

**Issue by janingo** [fluentform/fluentform#111]
Hi,

after a few updates again there is no more sending of Emails if the PDF is sett to be attached to admin or any other ones email.
Deactivating the possibility to attach PDF, emails will be send. As a serious buyer we tested any constallation before inquiry to sort out problems on our installation settings or hoster.
Pls. be so kind and update PDF addon to make it work again.

Thanks
Jan Ingo

**Comment by nkb-bd** [comment]
We could not reproduce the issue, please open a support ticket if you still face the issue.
Thanks
