### ISSUE TITLE
Imprint and Privacy Policy Missing on Landing Pages

### ISSUE THREAD

**Issue by bauhaus-Design** [fluentform/fluentform#113]
In most EU countries, a link to an imprint and a privacy policy must be provided on every page. 

I love the feature of "landing pages" but it would be great if they had a simple footer where imprint and privacy policy could be linked. In the picture I have designed a suggestion.

<img width="1440" alt="Bildschirmfoto 2021-07-15 um 13 58 23" src="https://user-images.githubusercontent.com/69368037/125784695-640d0821-a97b-4edc-9286-98b9a5c4ecbd.png">

**Comment by nkb-bd** [comment]
Thanks for the suggestion I will pass this to our team.
