### ISSUE TITLE
design/styles buttons in the priveiw window doesn't work 

### ISSUE THREAD

**Issue by ballonit** [fluentform/fluentform#116]
![Capture](https://user-images.githubusercontent.com/87765636/126496560-d423f8dd-8923-4039-9c3f-a4d858aa9b69.JPG)
![Capture1](https://user-images.githubusercontent.com/87765636/126496563-7da1a3ec-a2c1-4205-80eb-6e3afb567140.JPG)

**Comment by nkb-bd** [comment]
Could not reproduce the issue please open a support ticket https://support.wpmanageninja.com/.
