### ISSUE TITLE
Quotes break placeholders (MAJOR/URGENT)

### ISSUE THREAD

**Issue by yankiara** [fluentform/fluentform#12]
Hi,

Quotes break placeholders, both in Firefox and Chrome:

![Screenshot_3](https://user-images.githubusercontent.com/36680757/67074128-c9808480-f188-11e9-8d19-a5239976bf13.png)

**Comment by techjewel** [comment]
This is fixed in version 3.0.5

Thanks

**Comment by yankiara** [comment]
Great, thx!
