### ISSUE TITLE
Fields values or summary are not avalaible inside forms

### ISSUE THREAD

**Issue by yankiara** [fluentform/fluentform#13]
We should be able to use {all_data} and {inputs.field} syntax inside the form modules, so that we could dynamically display fields values in forms (at least in custom HTML module).

For instance, it is essential for multi-step forms to have a fields values summary at the last step, so that user can check data and go back to correct fields before submission.

**Comment by alex-authlab** [comment]
Hello @yankiara ,
You can now use input fields individually in step form and show input values dynamically.
Thanks
