### ISSUE TITLE
Bug relating to the Bump Form - Negative Sign not allowed on PayPal

### ISSUE THREAD

**Issue by Moss2710** [fluentform/fluentform#130]
How can this error be resolved? 

![Capture](https://user-images.githubusercontent.com/89684787/131212030-d90f7620-54d8-4396-9d94-99f7497f5d2b.JPG)
![capture 2](https://user-images.githubusercontent.com/89684787/131212034-79d443cc-dd2e-4c34-8d8a-156f37c3b780.JPG)
![capture 3](https://user-images.githubusercontent.com/89684787/131212036-ef234480-68ea-4823-96d0-0857beccd853.JPG)

The error only applies when adding a minus sign to the bump form with paypal checkout.

It does work with positive sign, but that is not the goal. The goal is to offer a discount.

**Comment by alex-authlab** [comment]
Hello @Moss2710 ,
Negative numbers will not with this feature, you can check out the coupon code module.
Thanks

**Comment by Moss2710** [comment]
Thank you

**Comment by Moss2710** [comment]
So wondering about the negative bump form in future development.

Just out of interest, how much would a modification to the code with an instruction to my developer cost? I don't have the money right now for custom development but once I launch the website and it takes off, if it does, then I will have enough enough.

**Comment by nkb-bd** [comment]
Why don't use a discount coupon instead
