### ISSUE TITLE
New lines not working in some mail clients in notifcation messages

### ISSUE THREAD

**Issue by njwgh** [fluentform/fluentform#132]
If you have a textarea in your form and a user creates new lines in their text in the textarea, then some email clients will concatenate the text onto all one line. (Specifically Outlook 2007, not sure about other Outlook versions).
This is for notification emails sent as HTML.

This is because the newline characters is sent by fluent forms as hex 0d0a which Outlook 2007 won't show as a new line.

Normally you would use a `<br/>`  tag to force a new line in emails.

A fix could be be accomplished by amending the 'fluentform_response_render_textarea' filter in \app\Hooks\common.php from:
`    return '<span style="white-space: pre-line">' . $value . '</span>';`
to
`    return '<span style="white-space: pre-line">' . nl2br($value) . '</span>';`

I have added a filter to my theme's functions.php on fluentform_response_render_textarea to make the above change and it works as expected.

Not sure if this is the best way to accomplish it or if there are others reasons NOT to have `<br/>` tags in a textarea

**Comment by nkb-bd** [comment]
This issue has been fixed please check with the updated version thanks.

**Comment by njwgh** [comment]
Thanks. Now working correctly :-)
