### ISSUE TITLE
Multiple Subscriptions

### ISSUE THREAD

**Issue by DoctorMicro** [fluentform/fluentform#134]
I'm hoping that Multiple Subscriptions can be added to a future update instead of getting the Error, _Sorry, multiple subscription item is not supported._

Example:

Website Hosting $15 per month
Site Maintenance $8 per month
Domain Name $8.50 one-time
**Total Price: $31.50**

Stripe Payments processing.

**Comment by alex-authlab** [comment]
I will add this as a feature request. Thanks for contacting for future feature request please check this https://trello.com/b/FaDlAD9B/public-roadmap-wp-fluent-forms
