### ISSUE TITLE
Text Area Border Controls not working

### ISSUE THREAD

**Issue by eno812** [fluentform/fluentform#139]
Please view this video to see what I'm referring to.

https://www.loom.com/share/5e39ebd20be045c683de2a1148a4ad8e

**Comment by alex-authlab** [comment]
Hello @eno812 ,
It is working fine here , could a be a script conflict, we will need more information to debug the issue , maybe you can open a support ticket here https://support.wpmanageninja.com/ and we will solve the issue for you.
Thanks
