### ISSUE TITLE
Submit a form does not work via android tablet or phone

### ISSUE THREAD

**Issue by gjkoetsier** [fluentform/fluentform#152]
Fluent forms is installed in wordpress and under windows submitting the form works fine using a windows PC but under android it does not work. The bar is changing to white but the submission is not completed (you don't see the message conforming the form submission).

**Comment by alex-authlab** [comment]
Which browser did you use, if you can let us know we will debug the issue.
Thanks

**Comment by gjkoetsier** [comment]
Safari in iOS 14 and 15 in an iPhone 

Hope this is enough information 

Regards

Gertjan 

Massagepraktijk Koetsier
Kameraarsweide 24
3437 CB  Nieuwegein 

Mobiel: 06-83871786
Web: https://mpkoetsier.nl
***@***.***

Verstuurd vanaf mijn iPhone

**Comment by alex-authlab** [comment]
It worked both on android and IOS, could be a site-specific issue, please open a support ticket here [http://support.wpmanageninja.com/](http://support.wpmanageninja.com/).
Thanks
