### ISSUE TITLE
Unable to send emails depending on the payment method

### ISSUE THREAD

**Issue by GiuseppeF-source** [fluentform/fluentform#159]
Unable to send emails depending on the payment method
![image](https://user-images.githubusercontent.com/52566060/141349574-36b13eda-e3fb-492b-b4ac-f91c8f766a53.png)
unlike the editor section, in the email notification section in the selection of the payment method it imposes a manual writing to which nothing can be matched.
For example, to select the offline payment method there could be two solutions: write Offline Payment or the Method Label inserted but in no case it works.

**Comment by alex-authlab** [comment]
Try using this https://prnt.sc/21yd768 it will work, for testing purposes you can print the payment method value on the confirmation page.

**Comment by GiuseppeF-source** [comment]
I cannot change the confirmation page based on the payment method for the same problem. In these sections, there is no condional logic with a drop-down box for the payment method. In other types of conditional logic we have drop-down boxes.
