### ISSUE TITLE
Radio Buttons can't "Deselect." 

### ISSUE THREAD

**Issue by NightSkyMurals** [fluentform/fluentform#160]
Is there any chance that y'all can fix the Radio Buttons so that they can be deselected if someone changes their mind. This seems like a problem for last century, not this one. :)

That's it... it would sure make the forms better if the buttons were delectable.

Thanks

**Comment by alex-authlab** [comment]
I suggest in this case you can use the checkbox, you can also limit the checkbox max selectable items using js. 
Thanks
