### ISSUE TITLE
Stripe Error: You may only specify one of these parameters: submit_type, subscription_data.

### ISSUE THREAD

**Issue by josjg** [fluentform/fluentform#161]
I have a form with a subscription field. Two options: monthly amount, yearly amount. User input amount is enabled for both options.
When I submit with Stripe payment selected I get the error message from Stripe: **_Stripe Error: You may only specify one of these parameters: submit_type, subscription_data._**
With Paypal as payment method selected I am taken to the Paypal and then get the error: **_Things don't appear to be working at the moment. Please try again later._**

I have both Stripe and Paypal set to test/sandbox mode.

I have set up Stripe IPN as per instructions on your support page.
The json export of my form is added (as a txt file)

[fluentform-export-forms-1-15-11-2021.json.txt](https://github.com/fluentform/fluentform/files/7538735/fluentform-export-forms-1-15-11-2021.json.txt)

Best regards,
Jos Gielen

**Comment by josjg** [comment]
I have some additional data for you:
When I us the filter 'fluentform_stripe_checkout_args' $checkoutArgs indeed gives both **submit_type** and **subscription_data**. The submit_type = "donate" and payment_type = "subscription". (in $submission) 
When payment_type is anything other than "**payment**" submit_type cannot be specified according to the Stripe API docs. (https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-submit_type)

This might be the reason for the warning above. (in the case of Stripe)

**Comment by josjg** [comment]
And another addition: 
1. Disregard the bug mentioned above regarding **Paypal**. I have fixed this, and it had nothing to do with Fluent forms.
2. With regards to the **Stripe bug** I added the following code snippet to remove the submit_type when the payment_type is "subscription". This fixes the error, but maybe you can update your code to do the same?

add_filter('fluentform_stripe_checkout_args', function ($checkoutArgs, $submission, $transaction, $form) {
    
	if($submission->payment_type == 'subscription') {
		if(array_key_exists('submit_type', $checkoutArgs)) {
			unset($checkoutArgs['submit_type']);
		}
	}
    return $checkoutArgs;
}, 10, 4);

**Comment by nkb-bd** [comment]
Thanks for the solution this issue has been fixed.
