### ISSUE TITLE
Filterable {all_data} Shortcode

### ISSUE THREAD

**Issue by black-eye** [fluentform/fluentform#162]
I was a bit suprised that the email notification shortcode {all_data} cannot be filtered, especially when I found it's current style a bit poorly arranged. Labels and values have each their own table rows, which takes up a lot of space.

Could you please add a filter on the line 321 in /app/Services/FormBuilder/ShortCodeParser.php? 
https://github.com/fluentform/fluentform/blob/fea836e7664f24a254befe99a3e390699fae7d57/app/Services/FormBuilder/ShortCodeParser.php#L321

Something like this: 
`return apply_filters( 'fluentform_all_data_custom_render', $html, $formFields, $inputLabels, $response );`

Here is the example of it's usage (basically the very same code as for default {all_data}, except the labels are in the same rows as values):

```
add_filter('fluentform_all_data_custom_render', function ( $html, $formFields, $inputLabels, $response ) {

    $html = '<table class="" cellpadding="0" cellspacing="0">';
    foreach ($inputLabels as $key => $label) {
        if (array_key_exists($key, $response->user_inputs) && \FluentForm\Framework\Helpers\ArrayHelper::get($response->user_inputs, $key)) {
            $data = \FluentForm\Framework\Helpers\ArrayHelper::get($response->user_inputs, $key);
            if (is_array($data) || is_object($data)) {
                continue;
            }
            $html .= '<tr><td style="width: 200px; vertical-align: top;"><strong>' . $label . ': </strong></td><td style="vertical-align: top;">' . $data . '</td></tr>';
        }
    }
    $html .= '</table>';

    return $html;
}, 10, 4);

```
I have tested it and it works just fine. I'm just not sure wheather `$formFields` has some use or not.

Thank you in advance, it would helped me a lot.

**Comment by alex-authlab** [comment]
Thank you for your suggestion we will this filter before our next update.

**Comment by black-eye** [comment]
> Thank you for your suggestion we will this filter before our next update.

That's good news, thank you. BTW, when the next update will be shipped? There hasn't been much updates recently, the last one was more than 3 months ago...

**Comment by black-eye** [comment]
> Thank you for your suggestion we will this filter before our next update.

Hi @alex-authlab, the new version is out, is this feature included? And if so, how can I use it?
Thanks

**Comment by alex-authlab** [comment]
Here is it 
apply_filters('fluentform_all_data_shortcode_html', $html, $formFields, $inputLabels, $response);

**Comment by black-eye** [comment]
> Here is it apply_filters('fluentform_all_data_shortcode_html', $html, $formFields, $inputLabels, $response);

Excellent thank you, will try it soon. It would be handy to include it to your docs and the changelog though.

![obrazek](https://user-images.githubusercontent.com/5634870/150137086-39f26a80-2483-4688-a7e3-16f9f266f46c.png)

**Comment by black-eye** [comment]
Hello again, @alex-authlab. I couldn't try the filter sooner, but I think you have a bug there, it doesn't work.

I think on the line 321-322 
https://github.com/fluentform/fluentform/blob/1f430fa6c72d0b9ec1e58ddc48f982847bcdfd98/app/Services/FormBuilder/ShortCodeParser.php#L321-L322 
there should be 
```
return apply_filters('fluentform_all_data_shortcode_html', $html, $formFields, $inputLabels, $response);
```
I've chnaged the line as suggested and it works for me.

Could you please fix it? Thanks
