### ISSUE TITLE
Cannot progress form to 'Next' for logged out users

### ISSUE THREAD

**Issue by marc-xap247** [fluentform/fluentform#169]
Troubleshooting for why the Next button wont allow a user to progress to the next page/step. This happens with both short codes inserted into a page as well as the Landing page URL.
I have disabled a few plugins like MalCare and a User Registration plugin, but problem remains.
In Fluent Forms, I have tried to deactivate User Registration integration. Also enabled No-Conflict mode. Disabled Honeypot Security.
Tried 2 different forms (different IDs), but the issue applies to all Forms.
Under Form settings, I have checked and ' Require user to be logged in' is disabled.

**Comment by marc-xap247** [comment]
I imported the form to a fresh wordpress site and the Fluent Form works fine. So, obviously plugin conflict somewhere which is annoying (time consuming).

**Comment by marc-xap247** [comment]
Today I have deleted both Fluent Form plugins and reinstalled. Same issue. The form works correctly for me as Admin user, but when for logged out users, the form opens correctly, but at the bottom of the first page after completing the questions, the 'next' button is dead and wont progress to page 2.

**Comment by marc-xap247** [comment]
I have deactivated most of the plugins ...LearnDash, WooCommerce, WC Subscriptions, WC Memberships. Also deactivated Booster Plus for WooCommerce and WP WC User Registration, and StoreCustomizer.

Switched the theme from Kadence to Twenty Twenty-One.

Still cannot get the Form to progress to page 2.

**Comment by marc-xap247** [comment]
OK, I found the conflict!!
It's LS Cache. I'm not sure which setting in LS Cache as yet. Will play with the settings now.

**Comment by marc-xap247** [comment]
OK, here is the troublesome setting. Turn off  JS Combine.
![2021-12-04 (2)](https://user-images.githubusercontent.com/87360205/144705426-ae22e657-843a-47e4-bdb2-aed5ee21ea4b.jpg)

**Comment by alex-authlab** [comment]
Thanks for your feedback as you can see the warning js combine may cause js error, so it is expected when turned on. Closing this ticket now, feel free to reach our support [http://support.wpmanageninja.com/](http://support.wpmanageninja.com/) if you face any other issues.
Thankss
