### ISSUE TITLE
Better Way to Handle the Default Error Messages

### ISSUE THREAD

**Issue by black-eye** [fluentform/fluentform#173]
I'd like to propose you a better way to handle the default Error Messages. 

**Current situation:** 
When you set the field as Required, the extra option for the Error Message is shown. This field is PRE-FILLED with the default message ("This field is required"). If the English is your language you're most likely fine with the phrasing and you can keep it as it is. But what if you use another language or you want to use "Fill in this field" instead of "This field is required" on all your forms and fields? Than you have to change it one by one for all the fields in all your forms you are using.

**Proposed solution:**
The Error Message field should not be pre-filled but used only as a placeholder (to show the user the default value). The field should be used only when a user wants to CHANGE the default value. The default value should be generated as a fallback, when no change has been made.

It would be also very helpful if we could change the default settings in one place (ideally for each used language).

This setting should be used for all the types of the (error) messages, e.g. for files/images uploads.

I think it's not a dificult change to make, but it would be a huge helper when managing the sites with lots of forms, especially when using a languages without the translation.

Thank you

**Comment by nkb-bd** [comment]
Hello @black-eye ,
Sorry for the delay, thank you for the detailed report and proposed solutuion. We have added this to our backlog our dev team will look into this.
