### ISSUE TITLE
Dropdown & Multi Select not working

### ISSUE THREAD

**Issue by b3dp** [fluentform/fluentform#175]
As in the attached video.

Normally there is no problem in saving the form, but Dropdown and Multiple Select operations do not save the form. It's been waiting for a long time.

I am using the latest version. All Wordpress is up to date.

What should I do ?

https://streamable.com/0qxod0

**Comment by alex-authlab** [comment]
Hello @b3dp ,
We could recreate the issue, can you please open a support ticket here [https://support.wpmanageninja.com/](https://support.wpmanageninja.com) , also attache your form as JSON zip we will try to recreate the issue with your form.
Thanks

**Comment by nkb-bd** [comment]
Closing the issue due to inactivity, feel free to reach us again anytime.
