### ISSUE TITLE
Format on Site Not Matching Preview + "Key" Appears in Checkbox Choices

### ISSUE THREAD

**Issue by aneshaf** [fluentform/fluentform#177]
Just updated to 4.3.
Bug: Form now showing "Key" within the checkbox fields.

Also, font in preview does not match what appears when you click live link on the site.

![272048705_10120807277306301_2475242274659606823_n](https://user-images.githubusercontent.com/89594499/150623195-3e8b7b5c-8fc4-416b-b1df-3bf24174fc75.jpeg)

![271971532_10120807294317211_4053597897091092659_n](https://user-images.githubusercontent.com/89594499/150623204-21123670-40ad-4bf3-a472-9b25dea691f7.jpeg)
![272251348_10120807304387031_188101972685252346_n](https://user-images.githubusercontent.com/89594499/150623205-fadf3e0e-5352-4507-b157-f4112fea8437.jpeg)

**Comment by alex-authlab** [comment]
Hello @aneshaf ,
Sorry for the delay , please update your design settings from admin this should work. Still if you face the issue, please open a support ticket `[here](https://support.wpmanageninja.com/)`.
Thanks
