### ISSUE TITLE
Text area {inputs.message} without lines break

### ISSUE THREAD

**Issue by iyadmn** [fluentform/fluentform#178]
The text area field allows the user to type multiple lines of text and recognizes Enters as line breaks.

But when sending the emails (notifications) the variable {inputs.message} creates the text of the message without line breaks.

The only temporary solution I've found to receive the message text with line breaks is to use 'pre' html tag for that variable.

I have searched your documentation and I don't see anything about it in the text areas, I have only found the following:

How to Customize a Conversational Form with WP Fluent Forms

[https://wpmanageninja.com/docs/fluent-form/advanced-features-functionalities-in-wp-fluent-form/how-to-customize-a-conversational-form-with-wp-fluent-forms/](url)

Hint for making a line break in Textarea: Add a hint for users to make a line break in the Textarea of the form.

Thanks in advance

**Comment by alex-authlab** [comment]
Thanks for reporting the issue, we will fix it soon.
