### ISSUE TITLE
Ugly Hard-coded Inline Style for Border Color of Upload File Preview

### ISSUE THREAD

**Issue by black-eye** [fluentform/fluentform#179]
Hello,

I'm trying to overide the default styles for the form and I'm struggling to do so for the File Upload Preview. After the file is uploaded, the script prints this inline style: `border: 1px solid rgb(111, 117, 125);`. Which is a bit unfortunate, because it's very hard to override. 

![obrazek](https://user-images.githubusercontent.com/5634870/152706865-c17abcae-6aa7-49be-8ed9-2579bddabffb.png)

It seems that the goal of this style is to highlight the fact that the file was uploaded successfully. But there's no reason to do so using the inline style - it would be better to use a class (e.g. ff-upload-preview-success), which could be overriden much more easier. 

Same goes for ff-uploaded-list outputting top-margin and font-size:

![obrazek](https://user-images.githubusercontent.com/5634870/152707187-345f0280-ee89-443c-8584-9c54105a09cc.png)

Why do use such aggresive techniques, which are so hard to override? (And these are not the only cases...)

Could you please look into this problem? Thanks

**Comment by nkb-bd** [comment]
We have added a CSS class for this.
