### ISSUE TITLE
Responsive Issue on Conversational form

### ISSUE THREAD

**Issue by shazardr** [fluentform/fluentform#180]
Form is not displaying correctly on mobile.
![back end](https://user-images.githubusercontent.com/99210770/152852928-dc6a66d6-49e1-4704-aee3-ceb8e6fdef7c.PNG)
![image0 (5)](https://user-images.githubusercontent.com/99210770/152852961-64a068a2-fd72-42ad-8a4a-a46fb67f634a.png)

**Comment by alex-authlab** [comment]
Can you temporarily disable your cache plugin and try again.

**Comment by nkb-bd** [comment]
Please open a support ticket, more info is needed to debug this.
