### ISSUE TITLE
Issue when downloading pdf

### ISSUE THREAD

**Issue by HemanAnnunto** [fluentform/fluentform#182]
Hello 
I hope you are fine

I am having an issue with plugin Fluent form when downloading a pdf file for user submission , the error occur is as follows :
**There has been a critical error on this website.**

Can you please advised me ?

Thank you

**Comment by alex-authlab** [comment]
Please make sure you have installed the fonts, from the notification shown in the plugin menu. This should resolve the issue, still, if you face the issue please open a support ticket [here](https://support.wpmanageninja.com/).
Thanks
