### ISSUE TITLE
Email Notification of form > Advanced settings not working

### ISSUE THREAD

**Issue by sarahAce** [fluentform/fluentform#183]
I am wanting to add another email address that will receive the notifications/form submissions. 
I'm going to the form > Settings > Email Notifications > Advanced > putting my email address in the CC area. 
Submitting a form, seeing the test send in my form submissions area, but I am not receiving any email notifications in regards to my submitted form.

**Comment by nkb-bd** [comment]
Try using an SMTP plugin like Fluent SMTP https://wordpress.org/plugins/fluent-smtp/ and make sure the email system is working in your site.
Thanks
