### ISSUE TITLE
ALL conditional logic fields show up in the email notification even if they weren't selected

### ISSUE THREAD

**Issue by trenttarala** [fluentform/fluentform#184]
Hello,

One of my clients has a custom ordering form on her website and its worked fine for months up until now. Essentially it works like this - the customer selects the "amount" of macarons they would like to purchase, and then depending on how many they want to purchase, they can then select the different flavors. The flavor fields are using conditional logic and only should pop up when after the "amount" is chosen. The issue i'm having is whenever someone places an order, every single field using conditional logic is included in the email. This hasn't happened before and I haven't touched the form in weeks so i'm not sure why this is happening now but not before.

 

Heres a link to the form:

https://www.livelovemacaron.com/order2/

I'll also include pictures of what it looks like in the email. Basically every field using conditional logic shows up in the email when usually it should just be one. As you can see in the screenshots i've included, i selected only "1 dozen" for the amount so only "1st dozen - First flavor" and "1st dozen - second flavor" should be popping up.

<img width="1239" alt="Screen Shot 2022-02-20 at 10 28 58 AM" src="https://user-images.githubusercontent.com/46792010/154851120-ef9036b3-99e4-4146-86d8-ffcd295fc01e.png">
<img width="598" alt="Screen Shot 2022-02-20 at 9 59 23 AM 1" src="https://user-images.githubusercontent.com/46792010/154851124-e4c80503-3049-4ced-afae-5f92ea558f18.png">
<img width="598" alt="Screen Shot 2022-02-20 at 9 59 23 AM" src="https://user-images.githubusercontent.com/46792010/154851127-ddde13a3-0d88-415b-bb8c-b9e71cb26e87.png">
<img width="598" alt="Screen Shot 2022-02-20 at 9 59 20 AM" src="https://user-images.githubusercontent.com/46792010/154851128-8b60f983-df26-415b-83d8-356a02c972e7.png">
<img width="598" alt="Screen Shot 2022-02-20 at 9 59 16 AM" src="https://user-images.githubusercontent.com/46792010/154851129-41e986a4-6897-4040-b39f-bc936cc05c14.png">
<img width="598" alt="Screen Shot 2022-02-20 at 9 59 08 AM" src="https://user-images.githubusercontent.com/46792010/154851130-7b5134e1-f4a1-40c3-a8d9-6c693ce5aacf.png">

**Comment by nkb-bd** [comment]
Thanks for reporting we will look into the issue.
Thanks
