### ISSUE TITLE
Unable to load all forms - Error: Something went wrong please try again later

### ISSUE THREAD

**Issue by chandu231** [fluentform/fluentform#190]
My Fluent forms stopped appearing on the list and not able to see the entries.

It was working fine and I have not installed any new plugins. 

I tried Deactivating and activating the plugin but no luck.

Please help.

**Comment by nkb-bd** [comment]
Hello @chandu231 ,
We will need additional information to find out the issue if possible create a screen recording of the issue with your console log open and open a support ticket [here](https://wpmanageninja.com/support-tickets/#/). 
Thanks
