### ISSUE TITLE
Payment summary Field Issue

### ISSUE THREAD

**Issue by mashrurFahim** [fluentform/fluentform#191]
I'm using fluent form pro version for one of my projects. It seems the payment summary field is not behaving accordingly as it should. Instead of showing the payment item name (I'm using **Radio Selection** as **Product Display Type** in the **Payment Field** option), it displays **Element Label** name which is pretty confusing and ambiguous.

Please have a look at that issue and give a proper solution to it.

Regards,
Mashrur Fahim

N.B.: This is the [Order Certificate Page](https://learndrive.org/order-certificate/) of the client site. Before the Purchase button, the **Payment Summary** field is applied.

**Comment by nkb-bd** [comment]
Hello @mashrurFahim,
Thank you for reaching out to us. We will fix the issue before the next update which going to be released next month. Until then you can use the payment input type as select fields, that will display correctly. 
But if you need this urgently you can open a support ticket [here](https://wpmanageninja.com/support-tickets/#/), and we will provide you a beta version with this fix.
Thanks
