### ISSUE TITLE
Radio button custom style issue

### ISSUE THREAD

**Issue by mashrurFahim** [fluentform/fluentform#192]
Hello,
There is an issue regarding radio button custom styling.

**Issue**: 
**Bug**: On the Elementor Fluent form widget, if I change the border-radius option of the radio button and checkbox section, it only updates for the checked status and the unchecked radio button remain the same.
**Expected behavior of issue 2**: Both unchecked and checked designs should be updated when the border-radius option is updated.

for more information please visit the site I worked on [Goolbay](https://goolbay.com). It is in the Attention seller section.

Regards,
Mashrur Fahim

**Comment by nkb-bd** [comment]
Thanks for reporting we have added this issue to our backlog, it will be fixed soon.
Thanks
