### ISSUE TITLE
Conditional Logic / Ignore required field

### ISSUE THREAD

**Issue by wingdu** [fluentform/fluentform#194]
Hello,

if a field has an Conditional Logic they ignore the required settings. 

<img width="1222" alt="Bildschirmfoto 2022-03-21 um 21 11 14" src="https://user-images.githubusercontent.com/20076066/159356063-da330cb4-e8d8-44a5-ad94-c6fd3af035c8.png">

**Comment by wingdu** [comment]
Screenshot 2

<img width="1034" alt="Bildschirmfoto 2022-03-21 um 21 14 21" src="https://user-images.githubusercontent.com/20076066/159356266-18ebbaa2-c8da-4d25-a88f-25a33ce1f686.png">

**Comment by wingdu** [comment]
ps: he also dont safe the provider data from the input fields

**Comment by nkb-bd** [comment]
We are discussing this issue in our support thread so closing this issue here.
