### ISSUE TITLE
Is it possible to restrict the number of characters in a number field?

### ISSUE THREAD

**Issue by trenttarala** [fluentform/fluentform#195]
One of my clients is trying to have a field field where the user HAS to submit at 15 character number. For example "1234 5678 9123 456" but it only allows you to edit the minimum and maximum values, NOT the amount of characters in the field. Is it possible to do this using javascript? I have the pro version so I have the option to add custom code. I don't know any Javascript myself but i was curious if it was even possible and/or if any of you know the piece of code i would need to add for this to work.

Any help would be highly appreciated, i'll paste the link to the site/form below. The field in particular that i'm referring to is called "quickbooks license number" under the fourth step.

https://www.enclavehosting.com/new-quickbooks-customer/

Thanks!

**Comment by adreastrian** [comment]
We are thinking of adding more validation rules. Until it's been implemented you may use the following code to extend the validation behavior.

```
add_filter('fluentform_validate_input_item_input_number', function ($error, $field, $formData, $fields, $form, $errors) {
    $yourFieldName = 'numeric-field';
    $numberOfDigitsYouWantToEnforce = 15;
    $yourValidationMessage = 'The number of digits has to be 15';
    
    $fieldValue = $formData[$yourFieldName];
    if (mb_strlen($fieldValue) != $numberOfDigitsYouWantToEnforce) {
        $error = $yourValidationMessage;
    }
    
    return $error;
}, 10, 6);
```

You can customize the behavior as you see fit. 

Thanks.

**Comment by trenttarala** [comment]
Thank you! One question though. When I click "advanced options" for a numeric field, there's no option to input any custom JS. I've used this feature for a "date" field in the past so I assumed there would be a custom JS area for the numeric field as well but I don't see one.

**Comment by adreastrian** [comment]
The numeric field doesn't have a JS area. Because there is no JS code is going on for this field.

The date field does have since it is rendered using JS.

However, if you want to add JS targeting a field, you can use the **Custom CSS/JS** settings.

**Comment by trenttarala** [comment]
Unfortunately the code didn’t work, It still allowed me to input 1-2 characters. Its supposed to be 15 exactly for this particular field. Ill attach a video and screen recording so that you can see what I’m seeing on my end.
[Graphical user interface, text, application  Description automatically generated]

From: Mahmudul Hasan ***@***.***>
Date: Friday, March 25, 2022 at 12:01 AM
To: fluentform/fluentform ***@***.***>
Cc: Trent Tarala ***@***.***>, Author ***@***.***>
Subject: Re: [fluentform/fluentform] Is it possible to restrict the number of characters in a number field? (Issue #195)
CAUTION: External Email!


The numeric field doesn't have a JS area. Because there is no JS code is going on for this field.

The date field does have since it is rendered using JS.

However, if you want to add JS targeting a field, you can use the Custom CSS/JS settings.
