### ISSUE TITLE
Conditional fields showing up all at once

### ISSUE THREAD

**Issue by smiciulis** [fluentform/fluentform#197]
Hi, 

There seems to be an issue with conditional fields across different forms on our website, some users see ALL fields even when conditional logic is not met (we have a form here https://www.co-hustle.com/survey/ that is designed to show specific questions based on the answers to previous questions, but some users get the whole thing at once). 

So far I've identified that opening up a new session in incognito mode on chrome typically makes this issue resurface and then if I try to refresh the screen, the issue goes away. 

I have tried disabling cache and turning of some other modules to test, but it seems like that does not affect the issue. Any suggestions?

**Comment by smiciulis** [comment]
Any chance someone can have a look at this? This is really affecting our user research as no one wants to fill a 20 question survey when it's only supposed to be 5? Help!

**Comment by nkb-bd** [comment]
Hello @smiciulis ,
Sorry for the delay, can you please open a support ticket [here](https://wpmanageninja.com/support-tickets/#/) with temporary access so we can look deeper it debug the issue, let us know if that's possible.
Thanks

**Comment by smiciulis** [comment]
Hi, thanks for getting back to me on this. I've created the ticket.

**Comment by HrDelwar** [comment]
Issue closed in support ticket id 43959.
