### ISSUE TITLE
{submission.admin_view_url} starts with "https//" (missing colon)

### ISSUE THREAD

**Issue by Heimkino-Praxis** [fluentform/fluentform#205]
I'm using {submission.admin_view_url} in email notifications.

The resulting email contains the link as intented, but it's missing the colon after https.

**Comment by HrDelwar** [comment]
@Heimkino-Praxis could not recreate the issue. Please update the plugin and check again.

**Comment by Heimkino-Praxis** [comment]
@HrDelwar The variable is used inside a text link. Maybe that's the reason.

![Google Chrome 2022-05-11 15 37 21](https://user-images.githubusercontent.com/16855812/167865260-054da898-c2b8-4871-9daa-bd4b34913fd0.png)

**Comment by nkb-bd** [comment]
Hello @Heimkino-Praxis ,
When you add a link from the editor it automatically inserts the  https, see [here](https://prnt.sc/Cz8oaycF253H) , you should click the settings (cog icon) and remove the https part cause it will be added from the shortcode. Then it will work.
Hope that helps, thanks.

**Comment by Heimkino-Praxis** [comment]
Okay, that solved it. Was a bit irritating, because the automatically inserted http:// (not https://) is not visible in the preview above.

Thanks a lot!
