### ISSUE TITLE
Conflict with WP Rocket js defer feature - forms don't work

### ISSUE THREAD

**Issue by aharonach** [fluentform/fluentform#206]
Hi,
I'm using your plugin as well as WP Rocket on the same website.

I ran into an issue where the form doesn't submit when WP Rocket is enabled with the js defer feature.

I'm getting this warning in the DevTools console:
`jQuery.Deferred exception: Cannot read properties of undefined (reading 'split') TypeError: Cannot read properties of undefined (reading 'split')
at m (/wp-content/cache/min/1/wp-content/plugins/fluentform/public/js/form-submission.js:1:3919)`

**I did my research and I found that the cause is as follows:**
in `wp-content/plugins/fluentform/app/Modules/Component/Component.php:557` you use an array key called "jquery_mask_vars" localizing the script `form-submission.js`. 
But what WP Rocket does is look for the word "jquery" inside inline scripts (localized objects are considered as inline as well),
and if there's a match, it wraps up the localized array with a `window.addEventListener('DOMLoadedContent')` code.
That's why the form cannot get the localized array that your plugin tries to enqueue along with the script, causing the form to stop working.

The solution is to delete the word "jquery" from that array key in line 557 (and of course use the updated key inside `form-submission.js`). 
I tested that and it fixed the issue I'm addressing here.

**Comment by nkb-bd** [comment]
Thanks for reporting , we have updated it.
