### ISSUE TITLE
Email Footer Text HTML doesn't work anymore

### ISSUE THREAD

**Issue by fmommeja** [fluentform/fluentform#207]
Hi,

since last release, the emails received by my clients get all the HTML tags in their footer!

The entire code set in **Global Layout Settings->Miscellaneous->Email Footer Text** is displayed instead of being interpreted.

Please fix this as soon as possible.

Kind Regards.

FM

**Comment by nkb-bd** [comment]
Thank you for reporting we have already fixed it in our development branch. It will be released with our next update.
