### ISSUE TITLE
Can't center align submission button with multi-step form

### ISSUE THREAD

**Issue by yankiara** [fluentform/fluentform#21]
Hi all,
In a multi-step form, the center align option for submission button has no effect because some CSS takes priority to align right.

![button center](https://user-images.githubusercontent.com/36680757/68380232-b9d4da00-014f-11ea-8f37-9017607e2248.jpg)

I think we should have the choice to keep the button centered even with multi-step.

Thx,
Yan

**Comment by nkb-bd** [comment]
If you use CSS with the form id or with an important tag it will work.
Thanks
