### ISSUE TITLE
Feature Request - Payfast integration

### ISSUE THREAD

**Issue by neural-oD** [fluentform/fluentform#214]
Hi.
What would it take to integrate Payfast payments for FluentForms?
This is the module that they've done for Gravity Forms: https://github.com/PayFast/mod-gravityforms/tree/master/gravityformspayfast

Is this something you could impliment on Fluent Forms?

**Comment by nkb-bd** [comment]
Thanks for reaching to us, we have added this as a feature request our team will look into it.
