### ISSUE TITLE
Create more than 6 containers.

### ISSUE THREAD

**Issue by jun1432** [fluentform/fluentform#216]
Fluent Forms Pro 4.3.7
Fluent Forms Pro Add On Pack 4.3.5

I tried to create this containers and cannot do so as the container is only limited to 6. 
https://www.screencast.com/t/9hTEitjxvW0y

Under all the heading texts are input text field. If I can add also a nested container would be great.

**Comment by nkb-bd** [comment]
We do not have any plans for nested container for now , maybe in future.
Thanks
