### ISSUE TITLE
Change of Format on Conversational form

### ISSUE THREAD

**Issue by Av1234isawesome** [fluentform/fluentform#217]
When creating the conversational form, it looks fine and functions on the preview, but when I use the link, the fonts change, it glitches and the check and multiple choice options are glitched as well. Not sure what can be done about this.

**Comment by nkb-bd** [comment]
We need to debug the issue, please open a support ticket [here](https://wpmanageninja.com/support-tickets/) , we will help you to resolve this.
Thanks
