### ISSUE TITLE
Email shortcode {all_data_without_hidden_fields} is displaying hidden fields

### ISSUE THREAD

**Issue by odaPuppy** [fluentform/fluentform#218]
I have a hidden field in my form, and when I email submission confirmations using the {all_data_without_hidden_fields} shortcode, the hidden field is still displayed.

**Comment by black-eye** [comment]
@HrDelwar 
I can confirm this issue. I think the problem might be this line: https://github.com/fluentform/fluentform/blob/bfe8bdbd5680b539a81722954ab57494ce12bf84/app/Services/FormBuilder/ShortCodeParser.php#L318

When I try to use FormFieldsParser::getInputsByElementTypes function in m shortcode, I get only empty field.

**Comment by HrDelwar** [comment]
@black-eye If you use both {all_data_without_hidden_fields} and {all_data} shortcode in same message the first was prioritized and others will not worked. 

In your smartcode callback higetInputsByElementTypes method first parameter is formId currently higetInputsByElementTypes method first parameter not support formId like  getAdminLabels or getEntryInputs. You must pass form object in first parameter. You can access form here like bellow
```
$form = $parser::getForm(); 
$hiddenFields = \FluentForm\App\Modules\Form\FormFieldsParser::getInputsByElementTypes($form, ['input_text', 'input_email', 'input_file', 'input_hidden']); 

```
Hope It will working.

**Comment by HrDelwar** [comment]
@black-eye If you use both {all_data_without_hidden_fields} and {all_data} shortcode in same message the first was prioritized and others will not worked. 

In your smartcode callback getInputsByElementTypes method first parameter is formId currently getInputsByElementTypes method first parameter not support formId like  getAdminLabels or getEntryInputs. You must pass form object in first parameter. You can get form here like bellow
```
$form = $parser::getForm(); 
$hiddenFields = \FluentForm\App\Modules\Form\FormFieldsParser::getInputsByElementTypes($form, ['input_text', 'input_email', 'input_file', 'input_hidden']); 

```
Hope It will working.

**Comment by HrDelwar** [comment]
@black-eye Currently not, we'll keep that in mind. [Here is ]( https://fluentforms.com/docs/fluent-form-php-api/) some docs, hope it will give you more references for working with fluentform api.
