### ISSUE TITLE
Syncing issue on live form

### ISSUE THREAD

**Issue by ganda-bhaskara** [fluentform/fluentform#221]
Hi- every time I am updating my form it seems doesn't synced with the live form, keep only showing the initial created form. Could you please help?

**Comment by HrDelwar** [comment]
Hello @ganda-bhaskara, couldn’t recreated this issue. It's maybe you site specific issue, maybe you have cash catch plugins. For troubleshooting the issue you can contact our supports with a ticket [here](https://wpmanageninja.com/support-tickets/).
