### ISSUE TITLE
Form Migrator fails on PHP 8

### ISSUE THREAD

**Issue by kylemccoy** [fluentform/fluentform#222]
Tried to import forms from Gravity using the Migrator, forms would not import unless I changed site PHP to 7.4

**Comment by ashleynvc** [comment]
Hello - I am having the same issue. My hosting provider says that support for PHP 7.4 is ending and will require an update to PHP 8. I tested this on my staging site and am getting the following errors showing for Fluent Forms:

Deprecated: Required parameter $position follows optional parameter $tags in /www/writewise_535/public/wp-content/plugins/fluentformpro/src/Components/Post/Components/PostContent.php on line 14

Deprecated: Required parameter $options follows optional parameter $correctValue in /www/writewise_535/public/wp-content/plugins/fluentformpro/src/classes/Quiz/QuizController.php on line 399

**Comment by nkb-bd** [comment]
Thanks for reporting we will fix it before our next update
