### ISSUE TITLE
Payment field not working consistently

### ISSUE THREAD

**Issue by lgovantes1** [fluentform/fluentform#224]
On my website, DJLU.FUN, I have created a payment form using the custom payment function but when you enter amount, the field for entering credit card information does not show up consistently... the first time it never shows up, then when you try again, it shows up sometimes, but other times no.  It fails regardless of device...PC, phone, etc.

**Comment by Taye2022** [comment]
I have the same issue.  PayPal not working consistently and form not displaying at all sometimes. Any help would be appreciated

**Comment by HrDelwar** [comment]
Hello @lgovantes1, @Taye2022 , In our side we don't recreate this issue. In [that form](https://djlu.fun/index.php/payment-form/) custom payment field also decimal formattable which is not implemented by default. Maybe there is conflict with custom payment fields. That's why payment method conditions not working perfectly. Please try with fresh custom payment field. If there is still problem contact our supports [here](https://support.wpmanageninja.com/support-tickets). Love from FluentForm Team.

**Comment by lgovantes1** [comment]
Habibur Rahman Delwar

This problem still exists.  My customers are having a lot of trouble with
payment.  When you go to https://djlu.fun/index.php/payment-form/  and
enter the amount, the credit card field does not show up on the first
entry.  If the form is reloaded, then it works, however, the field itself
is very hard to read because the lettering is a very faint gray.
*This is a critical issue and is NOT to be closed unless I can see this
working.  I see in your previous email you closed #224 as completed.*

*Luis Govantes*
*3215439161*
***@***.*** ***@***.***>*

**Comment by HrDelwar** [comment]
Hello @lgovantes1, In previous comment i mentioned you this form custom payment field have contain decimal formattable data-attribute which is only support in number field not implemented in custom payment field. Which is conflict payment method conditional logic. Your form

**Comment by lgovantes1** [comment]
I did what you suggested and this problem still exists.  I did, however, discover that removing the zip code check box seems to work.  This is NOT an acceptable solution, but I will use as a workaround for now.  Additionally, the Credit Card field text is VERY faint gray and needs to have a better default format.

**Comment by HrDelwar** [comment]
@lgovantes1 please create a support ticket [here](https://support.wpmanageninja.com/support-tickets) with attached this form exported json file and give me the ticket id.

**Comment by HrDelwar** [comment]
@lgovantes1 I look your form still exits decimal formattable data-attribute in coustom-payment-field, I don't know how you add this attribute witch not implemented by default. When delete that maybe some catch plugin catch that again. Please create a support ticket [here](https://support.wpmanageninja.com/support-tickets) with attached this form exported json file and give me the ticket id.
