### ISSUE TITLE
When adding new form, plugin is crashing

### ISSUE THREAD

**Issue by bedengler** [fluentform/fluentform#228]
I am on WP 5.7.6 and still using PHP 5.6 (need it for another application running on this server).

Everything works fine so far with the plugin, unless I'm adding a new form.
As soon as I'm pushing the button, Wordpress crashes and tells me, there has been a major error.
But the form gets created.
I can go back to WP Admin, but as soon as I try to edit the form, it crashes again.

Here's the error log I got from Wordpress:
`An error of type E_RECOVERABLE_ERROR was caused in line 991 of file /data/web/e51790/html/web-kasse2016.at/wp-content/plugins/fluentform/app/Modules/Registerer/Menu.php. Error Message: Argument 1 passed to FluentForm\App\Modules\Registerer\Menu::usedNameAttributes() must be an instance of FluentForm\App\Modules\Registerer\int, specified as an integer, called in /data/web/e51790 /html/web -kasse2016.at/wp-content/plugins/fluentform/app/Modules/Registerer/Menu.php on line 768 and defined`

**Comment by nkb-bd** [comment]
Hello @bedengler ,
We have identified the issue. You can open a support ticket [here](https://support.wpmanageninja.com/) with a temporary admin access so we can fix the issue for you.
Thanks

**Comment by nkb-bd** [comment]
Fixed
