### ISSUE TITLE
Form Not Working

### ISSUE THREAD

**Issue by pme-75** [fluentform/fluentform#229]
Hi,

I've implemented the plugin a year ago and it was working well until now but I recently realised that the form isn't going through anymore and I can't figure out the reason.

Any idea why it doesn't work ? 

Form available on this page: https://picmyevent.fr/contact/

Thanks for your help!

**Comment by nkb-bd** [comment]
Hello @pme-75 ,
It could be because of a plugin script conflict, if you recently added any new plugin try deactivating that or you can open a support ticket [here](https://wpmanageninja.com/support-tickets/), we will help you to fix the issue.
Thanks
