### ISSUE TITLE
Broken uploaded files links in notification emails

### ISSUE THREAD

**Issue by yankiara** [fluentform/fluentform#23]
Hi,

Sometimes the links for uploaded files are broken:
![links with accents](https://user-images.githubusercontent.com/36680757/68468871-3384ca80-0219-11ea-9698-03daa6ea0c23.jpg)
![links with accents 2](https://user-images.githubusercontent.com/36680757/68468873-3384ca80-0219-11ea-8d01-d1541f805a29.jpg)

Everything is OK in backend entries.

It seems that it comes from accents in filename, but not all of them, strange...
Might be a sanitizing/enconding problem.

Could you have a look, please?
Thx, Yan

**Comment by techjewel** [comment]
Thanks for reporting. I will definitely take a look and fix the issues
