### ISSUE TITLE
Not a bug, but a notice

### ISSUE THREAD

**Issue by nielsverwaal** [fluentform/fluentform#231]
Deprecated: Required parameter $position follows optional parameter $tags in /plugins/fluentformpro/src/Components/Post/Components/PostContent.phpon line14

**Comment by nkb-bd** [comment]
Thanks for reporting , its been fixed.

**Comment by nkb-bd** [comment]
If you need the updated code with this fix urgently please open a support ticket [here](https://wpmanageninja.com/support-tickets/) we will send it to you.

**Comment by nkb-bd** [comment]
Fixed
