### ISSUE TITLE
How to extract digits from string in shortcode?

### ISSUE THREAD

**Issue by 11208** [fluentform/fluentform#234]
I want to sent an Email Notifications with user input, but only digits.
Do we have a filter for a short code that can do this job?

Sample Input:  Code1234

"Your ID is {submission.code}".

Expected: "Your ID is 1234".

Is it possible to create a custom JS then parse the input like below?

"Your ID is {onlyDigits(submission.code)}".

Or filter maybe?

"Your ID is {submission.code | onlyDigits}".

Thanks in advance

**Comment by HrDelwar** [comment]
@11208  currently not possible, we will take it our feature request. You can use numeric field instead of text field and use {inputs.you_form_field_name} shortcode.
