### ISSUE TITLE
Condition Indicator not Displayed for Containers

### ISSUE THREAD

**Issue by black-eye** [fluentform/fluentform#237]
The little condition indicator ![obrazek](https://user-images.githubusercontent.com/5634870/190931724-0391a126-a432-49e7-bfd6-ca420fc54ffc.png) isn't displayed for Containers just for the regular fields.

You can see it here - all the rows have the conditions, but on the Containers the indicators aren't shown:

![obrazek](https://user-images.githubusercontent.com/5634870/190931868-5d73ca8b-982f-48e8-af6d-f31bb27a31ec.png)

Could you please fix it? It could be confusing. Thanks

**Comment by HrDelwar** [comment]
@black-eye Thanks for informing, hopefully it will be fixed before the next update.
