### ISSUE TITLE
Unequal Field Widths in Repeaters When Using Dropdowns And Inputs

### ISSUE THREAD

**Issue by black-eye** [fluentform/fluentform#238]
Using dropdowns and inputs together in the repeater leads to a rather disarranged look of the whole section. It's because the dropdowns have different widths than inputs.

See the image here:

![obrazek](https://user-images.githubusercontent.com/5634870/191382491-1d681219-b3b3-43f9-8a1b-27d51c168118.png)

(Just to be clear, in the image there are 3 different repeater fields, not the different rows of the same repeater.)

First and second rows are the almost same repeater fieds, the difference is just the lenght of the longest option (in this case the placeholder). The third row is the repeater with two inputs for the reference of the correct width distribution.

The reason is probably the way, how the table columns are calculated. For some reason, even when the select width is set to 100%, for the table calculation it has a different width than 100% width of the input. It's probably unsolvable unless you add some fixed widths to the columns depending on their count, or change the display type of the repeater.

BTW, are there any plans to add a custom widths for the repeater colums as you did with the containers? It would be quite ellegant solution to this problem.

Thanks

**Comment by nkb-bd** [comment]
Thanks for reporting, we will solve the issue, as for the custom width in repeater currently we do not have any plans maybe in future.

**Comment by HrDelwar** [comment]
Fixed in 4.3.16
