### ISSUE TITLE
JS Error When Trying To Process Forbidden File Type

### ISSUE THREAD

**Issue by black-eye** [fluentform/fluentform#242]
Hello, I came ascross this problem. When I try to upload a file type which is not allowed in WP (but is allowed in FF) I got this error:

```
POSThttps://www.preklady-spevacek.info/wp-admin/admin-ajax.php?action=fluentform_file_upload&formId=3
[HTTP/2 422 Unprocessable Entity 2711ms]
```

For a specific reason my WP site doesn't allow to upload .txt files. In FF there's only bulk option for all text types, including txt, so I'm not able to disallow txt files specifically. Not a big deal, FF can handle this situation and throws an error message as it should be done. But in addition to the frontend error it throws a JS error as well. 

You can try it on https://www.preklady-spevacek.info/overene-preklady-fluent-forms-test/#kalkulace - just try to upload any txt file.

Thanks for the fix

**Comment by nkb-bd** [comment]
Thanks ,for your information there is filter hook available for further modification of allowed file types, see [here](https://fluentforms.com/docs/fluentform_file_type_options/).
