### ISSUE TITLE
Ugly Thumbnail For Docx Document in Upload Fields

### ISSUE THREAD

**Issue by black-eye** [fluentform/fluentform#243]
Hello,

The thumb for docx uploads is not very useful - it show a wierd bunch of overlapped letters, totaly unreadable, as you can see here:

![obrazek](https://user-images.githubusercontent.com/5634870/197084170-eaf7b5a5-6c60-41a2-8a45-0f3af1234f93.png)

It's probably because the thumbnail tries to display something like this: `vnd.openxmlformats-officedocument.wordprocessingml.document` (official MIME type for docx).

Could you please display something more useful?

Thanks

**Comment by HrDelwar** [comment]
Hello @black-eye, Thank you for reporting. We will shipped it with fix in our next update.
