### ISSUE TITLE
Encoding Issue / Javascript and Labels replace " with &#039;

### ISSUE THREAD

**Issue by wingdu** [fluentform/fluentform#245]
After the Last Updates there is now a issue with encodings face on Labels and Javascript they replace " with &#039; also the ' with &#039; 

Bug: 
<label for=&#039;ff_3_name_first_name_&#039;>

Normal Layout has to be:
<label for="ff_3_name_first_name"> or <label for='ff_3_name_first_name'>

Same with Javascript... in parts the replace the ' with &#039;

**Comment by nkb-bd** [comment]
Thanks for reporting we have fixed the issue.
