### ISSUE TITLE
Item Quantity Element skipping numbers

### ISSUE THREAD

**Issue by panpullo** [fluentform/fluentform#249]
Hi!
Element which counts the quantity "Item Quantity" is bugged. 
My values are minimum 0 and maximum 20. If I click to count quantity - I can go 1, 2, 3 and after that it skips to 20. Counting down I can go 20,19,18,17 and after it it skips to 0. 
As I have it connected to order form, it is a great issue to me. 
Could you help me out, please? 

(I think it appeared after latest wordpress update 6.1.0)

Cheers

Jan

**Comment by HrDelwar** [comment]
@panpullo We have noticed it and have already fixed it in our development version. We will shipped it in our next update.
