### ISSUE TITLE
Multiple emails per "Configure Routing" > "Send To" field

### ISSUE THREAD

**Issue by kauaicreative** [fluentform/fluentform#254]
In Email Notifications is there a way to allow multiple emails to be sent in the "Configure Routing", "Send To" field. Currently this only works if I enter one email address per field. My client requires multiple emails.

"Routing
Allows notification to be sent to different email
addresses depending on values selected in the form."

**Comment by kauaicreative** [comment]
@nkb-bd Is this closed because it is now fixed?

**Comment by HrDelwar** [comment]
@kauaicreative No, not implemented yet. But we are added this to our internal backlog.
Thanks

**Comment by ASunday47** [comment]
I know this is closed, but +1 for the feature request.

**Comment by nkb-bd** [comment]
Merged with latest release
