### ISSUE TITLE
Help Video is broken

### ISSUE THREAD

**Issue by troyteeples** [fluentform/fluentform#265]
I went into the help to see if I could find an answer and noticed the help video was broken. Here's a link to what I saw. 
https://app.screencast.com/GwllbHX5T1YZo

**Comment by nkb-bd** [comment]
It's already fixed in our dev branch. Thanks for reporting.
Here is the correct [link](https://www.youtube.com/watch?v=M_r-4Ernjj0&list=PLXpD0vT4thWEpMEGqaEQaxTQ34ac2xzfb)
