### ISSUE TITLE
Sort & Filter group

### ISSUE THREAD

**Issue by rabienet23** [fluentform/fluentform#277]
Can you please, add Sort & Filter group to the fluent form entries in order to sort data from A to Z for example?

![Untitled-1](https://user-images.githubusercontent.com/126345174/221368952-bc2a9a46-3b5b-45e3-9bfe-b206c4f79b64.png)

**Comment by nkb-bd** [comment]
Thank you for reaching out to us, entries backend sorting is not possible as the entries are encoded in MySQL, we can add front end sorting. we will add this as a feature request.
