### ISSUE TITLE
400: invalid_request

### ISSUE THREAD

**Issue by Abu9860** [fluentform/fluentform#284]
You can’t sign in because Fluent Forms sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of Fluent Forms, see [error details](https://accounts.google.com/).
Error 400: invalid_request

**Comment by nkb-bd** [comment]
Can you give us a little more context, how can we reproduce the issue, and what module were you using? Also let us know your form link and existing plugins if possible. 
Thanks

**Comment by Abu9860** [comment]
So I was using fluent form  integration with Google sheet this error occer to get access code

**Comment by Abu9860** [comment]
Fluent Forms 4.3.24  and Fluent Forms Pro Add On Pack 4.3.12

**Comment by nkb-bd** [comment]
Please use the latest version of fluent form pro v4.3.23. As google updated its API we also updated it in our latest version. It should resolve the issue.
