### ISSUE TITLE
Form fields editing only in German

### ISSUE THREAD

**Issue by M4st3rITA** [fluentform/fluentform#287]
I accidentally realised that by editing FORMs (which have already been created in the past) I find all the 'Fields' in German.
My site is translated into 3 languages (including German) but the notice board is obviously in my mother tongue (Italian).
The only part in German is the 'Fields' part, the rest of the plugin is in English (as it has always been).

<img width="661" alt="Screenshot 2023-03-20 alle 16 40 01" src="https://user-images.githubusercontent.com/53777627/226391732-f4efad5f-d241-4809-ae7d-3a281e25bede.png">

**Comment by nkb-bd** [comment]
These are translated using the WordPress default function and procedure which follows the active translation. Ensure current language is set to English and the user language is set to as the site default. That should fix it, if not I suggest you open a support ticket [here](https://wpmanageninja.com/support-tickets/#/).
Thanks

**Comment by M4st3rITA** [comment]
Issue resolved, thanks for the help :)
