### ISSUE TITLE
PHP notice wpfluent form - oxygen builder

### ISSUE THREAD

**Issue by wpsumo** [fluentform/fluentform#29]
Php notices connected to oxygen builder:

`Notice (Suppressed)	Undefined index: multiple	1	-
wp-content/plugins/fluentform/app/Services/FormBuilder/Components/Select.php:22
FluentForm\A\S\F\C\Select->compile()
wp-content/plugins/fluentform/app/Services/FormBuilder/Components/Select.php:22
FluentForm\A\M\C\Component->FluentForm\A\M\C\{closure}()
wp-includes/class-wp-hook.php:288
do_action('fluentform_render_item_select')
Unknown location
FluentForm\F\F\Application->doAction()
wp-content/plugins/fluentform/app/Services/FormBuilder/FormBuilder.php:87
FluentForm\A\S\F\FormBuilder->buildFormBody()
wp-content/plugins/fluentform/app/Services/FormBuilder/FormBuilder.php:58
FluentForm\A\S\F\FormBuilder->build()
wp-content/plugins/fluentform/app/Modules/Component/Component.php:286
FluentForm\A\M\C\Component->FluentForm\A\M\C\{closure}()
wp-includes/shortcodes.php:325
do_shortcode_tag()
Unknown location
preg_replace_callback()
wp-includes/shortcodes.php:199
do_shortcode()
wp-content/plugins/oxygen/component-framework/components/classes/shortcode.class.php:54
CT_Shortcode->add_shortcode()
wp-includes/shortcodes.php:325
do_shortcode_tag()
Unknown location
preg_replace_callback()
wp-includes/shortcodes.php:199
do_shortcode()
wp-content/plugins/oxygen/component-framework/components/classes/div-block.class.php:47
CT_DIV_Block->add_shortcode()
wp-includes/shortcodes.php:325
do_shortcode_tag()
Unknown location
preg_replace_callback()
wp-includes/shortcodes.php:199
do_shortcode()
wp-content/plugins/oxygen/component-framework/components/classes/new-columns.class.php:50
CT_New_Columns->add_shortcode()
wp-includes/shortcodes.php:325
do_shortcode_tag()
Unknown location
preg_replace_callback()
wp-includes/shortcodes.php:199
do_shortcode()
wp-content/plugins/oxygen/component-framework/components/classes/section.class.php:57
CT_Section->add_shortcode()
wp-includes/shortcodes.php:325
do_shortcode_tag()
Unknown location
preg_replace_callback()
wp-includes/shortcodes.php:199
do_shortcode()
wp-content/plugins/oxygen-gutenberg/oxygen-gutenberg.php:115
Oxygen_Gutenberg->init()
wp-includes/class-wp-hook.php:288
do_action('init')
wp-settings.php:523
Plugin: fluentform`

**Comment by techjewel** [comment]
Thanks for reporting. Will be fixed in the next version.

**Comment by wpsumo** [comment]
So it's fixed now?

**Comment by wpsumo** [comment]
So it's fixed now?

**Comment by techjewel** [comment]
Yes it is.
