### ISSUE TITLE
Reopen: All the Caldera Forms Migrated All at Once, Even Though Selected Only One!

### ISSUE THREAD

**Issue by black-eye** [fluentform/fluentform#290]
Hello!
I'm not sure wheather you are still following closed issues, so I created new one. The issue is same as here: https://github.com/fluentform/fluentform/issues/278

Although the fix was announced almost 2 months ago, the issue is still there.

Could you please provide us with some more info?
Thanks

**Comment by HrDelwar** [comment]
Hello @black-eye, We are sorry for the delay. It has already been fixed in our developer branch. It has been added in our next release. Fixed beta version is given in below link.
https://drive.google.com/file/d/1QAEou4cZ-ga8B5GwA1hjaEuggHQd9rLL/view?usp=sharing

**Comment by black-eye** [comment]
@HrDelwar, thanks for the file.
I finally saved some time to check the fixed version and it seems to work fine. Are there any plans to release this fix before the new 5.0?

**Comment by HrDelwar** [comment]
@black-eye There are no plan to release any version before 5.0.0. In 5.0.0 the fix is attached. Feel free to test 5.0.0 beat version available in here https://drive.google.com/file/d/1U991Df5dDTjhdDmpQ694Wbvol4eYGThw/view?usp=sharing
