### ISSUE TITLE
Time Field BUG

### ISSUE THREAD

**Issue by onyxchase** [fluentform/fluentform#3]
Hello,

I created a form with a Date / Time selector, however it doesn’t register the proper time. Every time I choose a time, and exit the field, it makes it 1 hour less than what it should be. Very strange bug.

VIDEO: screencast.com/t/eiFAEYeeZ

**Comment by techjewel** [comment]
Hello @onyxchase,
Got the bug and thanks for letting us know. I am taking a look here now.

PS: We got your tickets too.

Thanks

**Comment by onyxchase** [comment]
Ok thank you. Sorry, I didn’t know exactly where to submit the bug information. Thank you for looking into it so quickly. Much appreciated! :-)

 

Jean

**Comment by onyxchase** [comment]
Ok thank you. Sorry, I didn’t know exactly where to submit the bug information. Thank you for looking into it so quickly. Much appreciated! :-)

**Comment by techjewel** [comment]
Please submit the support ticket at [https://wpmanageninja.com/support-tickets/](https://wpmanageninja.com/support-tickets/)

Thanks
