### ISSUE TITLE
iOS font-size too small

### ISSUE THREAD

**Issue by edoriv** [fluentform/fluentform#302]
Confirmation emails viewed on iOS are very small. When viewing the source code of the email there are multiple instances of the font -size being set to 14px. 14px is rather small 16px is considered a more standard font size for mobile. However even that still winds up far smaller than any other email I receive. I wanted to try to correct the email layout but it will take longer than a simple fix. I will continue to work on the email source. However a quick fix in the meantime that worked was to add the following to the end of the style template located in /fluentform/resources/views/email/template/styles.php

```
/* CSS styles for iOS devices - compensates for overly small font size on ios devices */
@media screen and (max-device-width: 768px) and (-webkit-min-device-pixel-ratio: 2) {
*{font-size:28px;}
*{line-height:1.3em;}
}
```

This will only force the larger font on iOS specifically.
Please consider including this as a work around unit a better solution can be found.
Updated to ensure line height is adjusted as well.

**Comment by edoriv** [comment]
I've found that if I set my own font sizes inline and layout then set the email type to send as raw html I can make something visually appealing. However if you do not do anything and use the default ALL shortcode the text is too tiny to read and requires some styling to ensure readability on iOS at least. The above style does help with this niche issue yet still allows to override in the design field if someone does go through the extra steps of hand making the email.

I found that creating the email in a page editor helps to make styling easier and installing Advanced Editor Tools plugin provides an easy visual way to set font sizes and build tables.

You can then copy and past this back into the confirmation email field.

I'd still suggest adding the above to the end of the CSS stylesheet to ensure a minimal readable experience for iOS.

**Comment by nkb-bd** [comment]
Thanks for sharing we have added this in our latest version.
