### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by Jacquitaloquita** [fluentform/fluentform#317]
Hello so new problems arrive, when in fluent forms pro dashboard go to the section INTEGRATIONS IT SAYS THIS

![image](https://github.com/fluentform/fluentform/assets/136031707/8c598afd-8b85-4097-98ff-9e7bdbbfee4b)

How to solve it?

**Comment by techjewel** [comment]
Most probably you are using an older version of Fluent Forms Pro. Please update Fluent Forms Pro to the latest version (verson 5.0.3)
