### ISSUE TITLE
Forms Not Deleting 

### ISSUE THREAD

**Issue by LiveStormChasers** [fluentform/fluentform#322]
Hey yall! 

I am trying to delete a created form and for some reason after clicking delete, nothing is happening. I have tried deactivating ALL plugins however the issue still persists. Any idea? I am using Version 5.0.6 of the plugin and Microsoft Edge.

**Comment by nkb-bd** [comment]
Failed to recreate the issue using Microsoft Edge, can you share a screenshot of your console log & network tab? Also, make sure your debug mode is turned off. If you can share a temporary admin access we can identify and solve the issue for you. You can use our official support portal [here](https://wpmanageninja.com/support-tickets/).

**Comment by LiveStormChasers** [comment]
Good morning! 

Oddly enough this morning it started working after failed attempts last night of the plugin not responding to the "delete" request. So as of now this problem solved itself and will mark as resolved. However, if you all wish to require more information on the problem I will be more than willing to work with you all on that! 

Thank you!
