### ISSUE TITLE
Checkboxes Module showing data as <ul> in PDF feeds.

### ISSUE THREAD

**Issue by alex-rankin** [fluentform/fluentform#325]
This is another issue to stack onto the newest fluent forms update.

Using the checkbox module and passing it to your PDF feeds using `{inputs.checkbox}` (or your value) results in the data displayed in a `<ul>` like the below.

```
<ul>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ul>
```

I have tried controlling these styles within the PDF feed with the below, but these do not apply no matter what selector I choose.

```
li {
  list-style-type: none!important;
  display: inline-block!important;
}

li:not(:first-child)::before {
  content: ","!important;
  padding-right: 0.5em!important;
}
```

Strangely this only occurs in the body of the PDF feed. The header and Footer act normally as before. (see last image)

**This is used to display as a comma list on the below Fluent versions:**
<img width="2358" alt="image" src="https://github.com/fluentform/fluentform/assets/71366782/9446df58-76c1-44fc-97e8-53b1a4b744ae">

**These are the versions errors are occurring:**
<img width="2360" alt="image" src="https://github.com/fluentform/fluentform/assets/71366782/0b28489d-5299-4b95-a71c-c58f649743d2">

**This show the differences between Header, Body and Footer.**
<img width="778" alt="image" src="https://github.com/fluentform/fluentform/assets/71366782/71206c07-4d66-4b99-95ea-fc7da64bcdb9">

Please could this be looked into as it is breaking alot of forms and pushing content onto pages it should not be!

**Comment by dhrupo** [comment]
Hi there, 

We have already noticed it. We will fix the bug in the upcoming release ASAP.

Thanks
