### ISSUE TITLE
Email notifications no longer working after most recent update

### ISSUE THREAD

**Issue by mark-bugbeecenter** [fluentform/fluentform#331]
Hello,

After updating both Fluent Forms and FluentSMTP all of our email notifications are now failing. Reason: bad request. We have not changed any other settings, any suggestions for troubleshooting?

Thanks,
M

**Comment by nkb-bd** [comment]
Try reconfiguring your fluent SMTP settings. Let us know if the issue remains.
Thanks

**Comment by mark-bugbeecenter** [comment]
Is there a support article or instructions on how to do so? We did not set up our own site.

**Comment by nkb-bd** [comment]
Check this https://fluentsmtp.com/docs/configurable-email-delivery-providers/

**Comment by mark-bugbeecenter** [comment]
I'll give that a try, thank you so much!
