### ISSUE TITLE
FluentForm doesn't respond

### ISSUE THREAD

**Issue by TechnoCoach** [fluentform/fluentform#339]
Hi,
I'm not able to modify or add fields to any forms.
I reinstall FForm without any effect.
Have you the same issue ?
![FFormIssue230802](https://github.com/fluentform/fluentform/assets/30630067/a23e9992-aa71-4368-b842-b29aeabb7d87)

**Comment by TechnoCoach** [comment]
![image](https://github.com/fluentform/fluentform/assets/30630067/c08770f1-8e49-46f4-889a-d3460172b9a0)
Debug is off and all versions reinstalled.

**Comment by nkb-bd** [comment]
Did you try temporarily deactivating another plugin to see if this was caused by other plugins? 
Please open a support ticket using the link above  and let me know the ticket ID.

**Comment by nkb-bd** [comment]
I have replied to your ticket, please check.

**Comment by TechnoCoach** [comment]
I have open a support ticket #75009

**Comment by HrDelwar** [comment]
Issue resolved on ticket #75009.
