### ISSUE TITLE
Line height → non responsive

### ISSUE THREAD

**Issue by pedcam** [fluentform/fluentform#345]
Hi,

I was trying to adjust the line height (Input&Textarea > Typography>Line Height) and while it works well on the preview window, the changes are not being reflected on the browser/frontend (doesn't seem to be a cache issue).
Regards, p

**Comment by HrDelwar** [comment]
@pedcam Please update to the latest fluentform version it should be resolved, if it doesn't, create a support ticket [here](https://support.wpmanageninja.com/#/tickets) with attached form zip file.
Thanks
