### ISSUE TITLE
Warnings and errors in FluentForm widget in Elementor 3.15

### ISSUE THREAD

**Issue by oligraph** [fluentform/fluentform#347]
Hello,

of late FluentForms is having a problem. It displays error messages in frontend like this (on top of the form)
![fluentforms-error-top](https://github.com/fluentform/fluentform/assets/9936382/f34900d8-0e0e-4ad3-8b12-f3e7cfb6f181)
![fluentforms-error-below](https://github.com/fluentform/fluentform/assets/9936382/9f352a6c-9092-4210-a374-32f7c60b2a61)
:
Warning: Undefined variable $captcha in /home/httpd/vhosts/pure-bodywork.ch/pure-bodywork/wp-content/plugins/fluentform/app/Hooks/filters.php on line 120

And below the actual form:
Warning: Trying to access array offset on value of type null in /home/httpd/vhosts/pure-bodywork.ch/pure-bodywork/wp-content/plugins/fluentform/app/Services/FormBuilder/FormBuilder.php on line 345

Elelementor 3.15.3 and Pro 3.15.1 respectively (latest)

Very happy for any hint on how to solve this. Thank you!

**Comment by HrDelwar** [comment]
@oligraph hi, look like FluentForm Global Setting > Miscellaneous -> Auto Load Captcha is enabled but no captcha type is selected. If it is not necessary disable auto load captcha, otherwise select captcha type and save again. Hope this solves your problem.

**Comment by oligraph** [comment]
Hello, Habibur Rahman,

thank you for your prompt reply. I cannot uncheck the «Auto Load captcha» option, because it is uuhm greened out:



[ Olaf Müller ][ Mittlere Strasse 35 ][ 3600 Thun ]
------------------------------------------------------------------------------
[ Phone +41 33 221 52 39 ][ Mobile +41 78 767 99 60 ***@***.*** ]
Am 22. Aug. 2023, 13:06 +0200 schrieb Habibur Rahman Delwar ***@***.***>:

**Comment by oligraph** [comment]
Hello, Habibur Rahman,

(sorry, I pressed some unknown keyboard shortcut and the mail went off too soon)

thank you for your prompt reply. I cannot uncheck the «Auto Load captcha» option, because it is uuhm greened out:



Do I have to fill in some captcha credientials and then deactivate the button?

Thanks for your help so far, it’s greatly appreciated

Olaf

[ Olaf Müller ][ Mittlere Strasse 35 ][ 3600 Thun ]
------------------------------------------------------------------------------
[ Phone +41 33 221 52 39 ][ Mobile +41 78 767 99 60 ***@***.*** ]
Am 22. Aug. 2023, 13:06 +0200 schrieb Habibur Rahman Delwar ***@***.***>:

**Comment by oligraph** [comment]
Friend Habibur Rahman,

I solved the issue by reentering hCaptcha keys, then turning off the Auto thing. And the error code is no longer displaying.

Greatest of thanks,

May you live a long and fulfilled life

Olaf

[ Olaf Müller ][ Mittlere Strasse 35 ][ 3600 Thun ]
------------------------------------------------------------------------------
[ Phone +41 33 221 52 39 ][ Mobile +41 78 767 99 60 ][ ***@***.*** ]
Am 22. Aug. 2023, 13:06 +0200 schrieb Habibur Rahman Delwar ***@***.***>:

**Comment by HrDelwar** [comment]
Thank you for staying with FluentForm. Have a good day.
