### ISSUE TITLE
Braintree integration?

### ISSUE THREAD

**Issue by LogProd** [fluentform/fluentform#351]
I don't see that PayPal's Braintree for accepting credit card payments is yet integrated into FluentForms.

As one of the most popular credit card processors for small businesses because it doesn't have monthly fees, it would be wonderful to see this supported. This would  be a substantial move at jumping ahead of competition. 

I hope this is possible in the next update.

**Comment by nkb-bd** [comment]
Thanks for your feature request. I will pass it on to our team.
