### ISSUE TITLE
Send daily entries

### ISSUE THREAD

**Issue by giorgos-kritikos** [fluentform/fluentform#356]
Hello,

My company wants to automatically send the daily entries by mail in excel format at a predetermined time.
I want to create a form where parents will declare that the child will not come to school today.

**Comment by giorgos-kritikos** [comment]
Also i need to scedule every day closes form automatically and reopen next day.

Thanks

**Comment by dhrupo** [comment]
Hi,
There is no direct way to achieve your requirements with Fluentforms. But you can open a support ticket for a custom workaround if any is available.
Thanks
