### ISSUE TITLE
conflict with Elementor

### ISSUE THREAD

**Issue by Rafaelbarlev** [fluentform/fluentform#36]
Hello Fluent Form support,
I’m facing a conflict issue between Fluent Form and Elementor in one of my pages it’s a registration page.
I was in contact with Elementor Support team and at their advice I’m contacting your support.
Here is a copy of the relevant communication I had with Elementor.
A video which illustrate the issue:
אלמנטור | somatic on line - Watch Video

https://www.loom.com/share/98f7a8ff93b8484da8229cc9ad860bcc

And Elementor last reply:
The Fluent Forms plugin is causing the issue by overriding the Elementor's flatpickr styles:
We kindly recommend reporting this issue to the third-party plugin author, they'd be in a better position to address this issue or assist you with this. If they need any help from us, they can open an issue on our Github account and our developers will be happy to assist.
https://github.com/elementor/elementor/issues

Feel free to contact us in case you need further assistance. We’d be happy to help.

Thank you very much,
Rafael

**Comment by techjewel** [comment]
@Rafaelbarlev 
Thanks for reporting this issue. We will take a look about this and check what's making the issue.
