### ISSUE TITLE
DateTime use start_of_week option

### ISSUE THREAD

**Issue by LexXxurio** [fluentform/fluentform#361]
Hi guys,

it would be nice if you could use the wordpress option start_of_week to set firstDayOfWeek in flatpickr.
Currently we use this hook to achieve that:
```php
add_filter('fluentform/date_i18n', function ($i18n) {
    $i18n['firstDayOfWeek'] = (int) get_option('start_of_week');
    return $i18n;
});
```

**Comment by nkb-bd** [comment]
Thanks, we will add this in our next version.
