### ISSUE TITLE
email routing notifications are not sent

### ISSUE THREAD

**Issue by awyndy** [fluentform/fluentform#365]
i was able to create the email routing for 25 different selection list values, however the notifications are not sent even though the logfiles show that the notification was sent

also no notification arrives in the spam folder

any idea what the problem could be?

**Comment by nkb-bd** [comment]
First, check if email configuration settings , and sending email from your server are working properly or not. Email sending is not handled buy fluent form ,WordPress handles it or you can use smtp plugin like fluent Smtp, some time default WordPress email handling does not work as expected.

**Comment by awyndy** [comment]
thank you so much for your quick and helpful feedback!

**Comment by nkb-bd** [comment]
Closing this issue feel free to reach us agani if you need anything else.
