### ISSUE TITLE
Display error when processing form

### ISSUE THREAD

**Issue by Aftershok** [fluentform/fluentform#37]
I created a form and placed it into my Elementor layout using the form's shortcode. When the form is processing the request (after clicking the submit button), the spinner that appears next to the button has a repeating visual glitch. Here's a screen capture:

https://v.usetapes.com/gDZaUG0Wgl

Can this be fixed? The form works fine, but it looks a little unprofessional. Thanks!

**Comment by techjewel** [comment]
Hello @Aftershok 
Thanks for reporting, We are going to fix in our next version.

**Comment by Aftershok** [comment]
Excellent! Thank you!
