### ISSUE TITLE
View Visual Graph, not updating all graphs to selected time

### ISSUE THREAD

**Issue by neural-oD** [fluentform/fluentform#370]
Hi, 
Not sure if this is meant behaviour, but when I select to view visueaol graph, if I select a different time, it only affects the bar graph - submission stats. However, other graphs shown, as in advanced field report, are not updated with the dates filter.

Is this intended behavior, or is it a bug.

**Comment by nkb-bd** [comment]
This is intended, the date field is for Submission Stats, and Advance Field Report is separate from this.

**Comment by neural-oD** [comment]
Thanks for confirming
