### ISSUE TITLE
WP Fluent Forms Customisation of button colours is reverting to default

### ISSUE THREAD

**Issue by sevilla8623** [fluentform/fluentform#371]
Submit button > custom style. Changed the background, on hover background, and text colors - they displayed on the form correctly, until I saved the form, then reverted to default light grey.
The same issue as https://github.com/fluentform/fluentform/issues/75
FluentForm Version 5.1.2
WordPress 6.4.1

**Comment by nkb-bd** [comment]
Please update to the latest fluentform version it should be resolved, if it does not work share your form url.
Thanks
