### ISSUE TITLE
Shortcodes not working

### ISSUE THREAD

**Issue by Yelto1966** [fluentform/fluentform#4]
Tried this on a number of themes but will not show, form in front end

**Comment by techjewel** [comment]
Hello @Yelto1966 ,
Would you please share the URL so I can take a look. FluentForm should work on any theme.

Thanks

**Comment by Yelto1966** [comment]
Hello techjewel
See below
https://staff-management.arkotraining.co.uk/sample-page/

**Comment by techjewel** [comment]
Hello @Yelto1966 ,
Would you please export the form from backend and send to support[at]wpmanageninja.com
I may need to see the errors it's encountering in your use case. 

Thanks

**Comment by Yelto1966** [comment]
Its on its way

**Comment by techjewel** [comment]
Resolved
