### ISSUE TITLE
Enable Auto Tab-Index Breaks Repeat Fields

### ISSUE THREAD

**Issue by SteveCorbett** [fluentform/fluentform#40]
When "Enable Auto Tab-Index" is enabled in the Global Layout Setttings, it is not possible to add extra lines to a repeat field. The problem lies in the following code:

            function(e) {
                e.on("click", ".js-repeater .repeat-plus", function(e) {
                    var t = jQuery(this)
                      , n = t.closest("table")
                      , a = t.closest("tr")
                      , i = parseInt(n.attr("data-max_repeat"))
                      , o = n.find("tbody tr").length;
                    if (i && o == i)
                        n.addClass("repeat-maxed");
                    else {
                        var l = a.clone();
                        l.find("td").each(function(e, t) {
                            var n = jQuery(this).find(".ff-el-form-control:last-child")
                              , a = n.attr("tabindex")
                              , i = {
                                value: "",
                                id: "ffrpt-" + (new Date).getTime() + e
                            };
                            a && (i.tabIndex = parseInt(a) + itemLength),
                            n.prop(i)
                        }),
                        l.insertAfter(a);

The problem is that "itemLength" is not defined.

**Comment by nkb-bd** [comment]
Thanks for reporting we will look into the issue.
