### ISSUE TITLE
[Feature Request] Make HTML executable on form elements and options

### ISSUE THREAD

**Issue by crossfire91** [fluentform/fluentform#401]
I would love to add HTML tags to my form elements and options. F.e. to make something bold or put a link.
In the EU people f.e. need to select a checke box 'I accept the privacy policy' and privacy policy should be a LINK to my privacy policy.

But when I put it like: I accept the `<a href='https://urlToMyPrivacyPolicy.com'>`privacy policy`</a>` it is not composed. 
Please make that work...

**Comment by nkb-bd** [comment]
I am not sure what you mean by composed but basic html works inside field element label. See attached screenshot.

<img width="210" alt="image" src="https://github.com/fluentform/fluentform/assets/48018765/3c649c37-5406-4272-a9e4-60d8cb900c51">

**Comment by nkb-bd** [comment]
Html support is already added
