### ISSUE TITLE
Mautic add-on feed

### ISSUE THREAD

**Issue by bambabes** [fluentform/fluentform#41]
Mautic integration field labels are missing from the options.  State is one of them.  App shows Address, city, zip, and country, but I'm unable to select state.  

![image](https://user-images.githubusercontent.com/66431608/83778487-c7f0c780-a658-11ea-9263-2b85fd56c652.png)

**Comment by alex-authlab** [comment]
Hello @bambabes,

We have noticed and already fixed the issue. It will be available with the next update mautic addon update.

Thanks
