### ISSUE TITLE
Form Steps will Anchor the top of the form

### ISSUE THREAD

**Issue by bean4896** [fluentform/fluentform#43]
Form Steps Field click  "Next" or "Previous" will anchor the top the form which i think is not user friendly. Especially in mobile sometimes i get bug, anchor to the bottom of the page ....

**Comment by alex-authlab** [comment]
Hello @bean4896 ,
You can disable the auto-scroll by turning off the autofocus change, see [here](https://prnt.sc/10hnpvr).
Please let us know if you face any more issues.
Thanks
