### ISSUE TITLE
To web site: Feature table list

### ISSUE THREAD

**Issue by paaljoachim** [fluentform/fluentform#437]
It would be helpful to have a feature table list comparing the free vs premium versions to see what is included in each. I went to the web site and could not find any easy comparison between the two.

It is a good selling point having a table with a kind of standard checkmarks showing what is in free and what is in premium versions of the plugin. It needs to be easy to read as one can quickly go through it. This is very different compared to the premium features overview screen. But it is very helpful to have this quick overview of features table list.

**Comment by nkb-bd** [comment]
There is a footer link here 
[https://fluentforms.com/free-vs-pro/](https://fluentforms.com/free-vs-pro/)
