### ISSUE TITLE
A bigger field inserter area so one does not need to scroll

### ISSUE THREAD

**Issue by paaljoachim** [fluentform/fluentform#438]
Currently the field inserter looks like this:

![Screenshot 2024-07-07 at 13 26 41](https://github.com/fluentform/fluentform/assets/5323259/c689c28d-37d7-435d-a35d-cbf77335424c)

One has to scroll to the fields in the bottom of the inserter to see what these are. The inserter area fields a bit cramped/small and could be made bigger so one can see all the fields in example General at once.

Here is a suggestion. 

![Fluent Forms new field inserter](https://github.com/fluentform/fluentform/assets/5323259/6134f2da-bc68-4ea2-b94f-d54f8702e79c)

It is bigger and gives more space to see all the fields so that one does not need to scroll.

**Comment by HrDelwar** [comment]
@paaljoachim Thank you for your advice. While I understand the value of being able to see all the fields at once, I believe that organizing the fields in the insert area into three columns improves the overall visual layout. Additionally, scrolling requirements should not create significant complexity. Nevertheless, we will consider your input carefully and discuss further with our UI team.

**Comment by paaljoachim** [comment]
For me it is about visibility right away getting a quick overview of fields. Scrolling means that one will need to remember to scroll and that things are not visible right away.  Thank you for the reply @HrDelwar
