### ISSUE TITLE
Submission Notes - remove "Sorry, No Notes found!"

### ISSUE THREAD

**Issue by paaljoachim** [fluentform/fluentform#444]
In Submission Notes I see this:

![Screenshot 2024-07-08 at 14 40 11](https://github.com/fluentform/fluentform/assets/5323259/37e4d46e-beee-4de0-9912-1943a79f8b04)

It seems weird to have the text: "Sorry, No Notes found!"
As it is myself/user whom will need to add Submission notes if needed. Most of the time I believe it is not needed.
Please remove the text and just keep it blank.

Replace with:
![Submission Notes blank](https://github.com/fluentform/fluentform/assets/5323259/923e5e4e-d3dd-4100-a070-90da71ad22bf)

**Comment by HrDelwar** [comment]
@paaljoachim Thank you for your suggestion. We will look into it.
