### ISSUE TITLE
Email Notifications: Sending to multiple emails?

### ISSUE THREAD

**Issue by paaljoachim** [fluentform/fluentform#445]
Contact Form -> Email Notifications.

![Screenshot 2024-07-09 at 08 17 30](https://github.com/fluentform/fluentform/assets/5323259/bac88add-2aca-4b1a-a222-0838a18ee2d0)

Send to Email.
It is not clear to me if the email can go to multiple email addresses. That one can just use a , comma between email addresses.
Like: email address 1, email address 2.

Btw it would be nice with a CC and/or BCC field to send admin email submissions to.

**Comment by nkb-bd** [comment]
Added placeholder "Use comma for multiple values" & from advanced you can add cc or bcc

**Comment by paaljoachim** [comment]
Hey @nkb-bd 

Where is the placeholder added?
I am not seeing any mention of "Use comma for multiple values" in the top area or bottom area of the notifications.

**Comment by nkb-bd** [comment]
Its on dev build, added for next release, thanks

<img width="1055" alt="Image" src="https://github.com/user-attachments/assets/94c4761d-201e-4360-a8d7-ea9b866039e5" />

**Comment by paaljoachim** [comment]
Great thanks!
