### ISSUE TITLE
Add punctuation to Confirmation Settings message

### ISSUE THREAD

**Issue by paaljoachim** [fluentform/fluentform#463]
This is what I see as the confirmation message.

![Screenshot 2024-08-05 at 17 13 54](https://github.com/user-attachments/assets/5569f17d-6240-4e6c-9482-b139273eb5a6)

The first sentence has a punctuation. The second sentence does not.

Please add the punctuation to the second message so it becomes:
Thank you for your message. We will get in touch with you shortly. <- Added a punctuation at the end of the sentence.

**Comment by nkb-bd** [comment]
Fixed for next version
