### ISSUE TITLE
Fluent Forms Pro - Email Notifications section 3 dot bug

### ISSUE THREAD

**Issue by paaljoachim** [fluentform/fluentform#474]
Hey

In the Email Notifications section. In the Advanced section.
Scrolling down to Reply to. I click the 3 dots and get this:

![Fluent Forms Pro Bug](https://github.com/user-attachments/assets/a991c436-871d-4cc8-8901-9e1ffe221485)

I notice the same error are also in multiple 3 dots areas.

**Comment by nkb-bd** [comment]
Can you share your form fields ,it seems you may have a empty forms.

**Comment by paaljoachim** [comment]
Here are the Form fields.

![Screenshot 2024-09-19 at 08 05 49](https://github.com/user-attachments/assets/dc510da7-ec3f-4808-a7e2-2fdfab895e23)

**Comment by nkb-bd** [comment]
It seems none of them are email fields

**Comment by paaljoachim** [comment]
Ahh. Yes you are right. I forgot to add the email field.
I went ahead and added the field and now the 3 dot button works.

The question now comes up... should there be a default message that shows up if no email field has been added?
Such as "Email field is missing" instead of nothing.

**Comment by nkb-bd** [comment]
Yes instead of blank there should be some indication, we will do that, Thanks
