### ISSUE TITLE
Page Unresponsive

### ISSUE THREAD

**Issue by jeremymccarron** [fluentform/fluentform#48]
Some users (about half so far) are experiencing a "Page Unresponsive" error when filling out the Fluent Form on my Wordpress Site https://accesstojusticebc.ca/share-your-story/

**Wordpress**
_WP Version | 5.5.1
Beaver Builder Theme 1.7.5.1
Beaver Builder Child Theme 1.0_

**Server**
_Server architecture	Linux 4.4.216-1.el6.elrepo.x86_64 x86_64
Web server	Apache
PHP version	7.3.12 (Supports 64bit values)_

**Database**
_Extension	mysqli
Server version	5.7.26-29-log_

**Plugins**
_Akismet Anti-Spam	Version 4.1.6 by Automattic | Auto-updates disabled
Beaver Builder Plugin (Pro Version)	Version 2.3.2.5 by The Beaver Builder Team (Latest version: 2.4.0.5) | Auto-updates disabled
CoBlocks	Version 2.0.2 by GoDaddy (Latest version: 2.4.0) | Auto-updates disabled
Duplicate Post	Version 3.2.4 by Enrico Battocchi (Latest version: 3.2.6) | Auto-updates disabled
Essential Grid	Version 2.3.6 by ThemePunch (Latest version: 3.0.7) | Auto-updates disabled
Fluent Forms - Best Form Plugin for WordPress	Version 3.6.31 by WP Fluent Forms (Latest version: 3.6.51) | Auto-updates disabled
Fluent Forms PDF Generator	Version 1.0.0 by WPManageNinja LLC (Latest version: 1.0.1) | Auto-updates disabled
Fluent Forms Pro Add On Pack	Version 3.6.31 by WP Fluent Forms | Auto-updates disabled
Font Awesome	Version 4.0.0-rc20 by Font Awesome | Auto-updates disabled
Google Fonts Typography	Version 2.1.1 by Fonts Plugin (Latest version: 2.2.4) | Auto-updates disabled
Ninja Forms	Version 3.4.24.3 by Saturday Drive (Latest version: 3.4.30) | Auto-updates disabled
Ninja Forms - Addon Manager	Version 3.0.13 by The WP Ninjas | Auto-updates disabled
Ninja Tables	Version 3.5.12 by WPManageNinja LLC (Latest version: 4.0.2) | Auto-updates disabled
Ninja Tables Pro	Version 3.5.12 by WPManageNinja | Auto-updates disabled
Sucuri Security - Auditing, Malware Scanner and Hardening	Version 1.8.24 by Sucuri Inc. | Auto-updates disabled
Tag Groups	Version 1.29.0 by Chatty Mango (Latest version: 1.35.1) | Auto-updates disabled
WordPress Importer	Version 0.7 by wordpressdotorg | Auto-updates disabled
Yoast SEO	Version 14.4.1 by Team Yoast (Latest version: 15.0) | Auto-updates disabled_

It doesn't appear to be related to the speed at which the users are entering the information (i.e. not timing out), or file uploads associated with the submission (e.g. tried submitting both with and without attachments). 

Assuming this is browser/extension related... Is there anything I can do to stop it from happening?

![Screen Shot 2020-10-05 at 8 51 58 PM](https://user-images.githubusercontent.com/23056832/95241920-56ba5000-07c3-11eb-9b93-69618823c33d.png)

Thank You!

**Comment by techjewel** [comment]
hello @jeremymccarron 
Would you please export the form submit at https://wpmanageninja.com/support-tickets/ so we can take a look and find the issue?

Thanks

**Comment by jeremymccarron** [comment]
There is no form submit entry, unfortunately. The page becomes unresponsive and the user is unable to submit.
