### ISSUE TITLE
Missing `getEnv` method

### ISSUE THREAD

**Issue by Saggre** [fluentform/fluentform#486]
The `getEnv` method called in the two lines below does not seem to exist.

https://github.com/fluentform/fluentform/blob/ce6cb102855a68f7e042f286fec34978578e3327/app/Hooks/actions.php#L667

https://github.com/fluentform/fluentform/blob/ce6cb102855a68f7e042f286fec34978578e3327/app/Hooks/actions.php#L703

Resulting in `Uncaught Error: Call to undefined method FluentForm\Framework\Foundation\Application::getEnv() in /var/www/html/wp-content/plugins/fluentform/app/Hooks/actions.php:703` when trying to log integration responses through `IntegrationManagerController::logResponse`

**Comment by nkb-bd** [comment]
This is fixed in our dev branch will be released soon.
