### ISSUE TITLE
Questions with conditional logic showing up when they should not

### ISSUE THREAD

**Issue by morgancarrie** [fluentform/fluentform#49]
Two questions are suddenly showing up on the survey page that should only appear if the "How likely to recommend..." question has a score of seven or lower. Example: https://azwindowreplacement.com/customer-survey/ 

![Fluent-Form-glitch-1-101220](https://user-images.githubusercontent.com/72838874/95926243-aa530d80-0d70-11eb-9da0-99a85fc69d30.jpg)
![Fluent-Form-glitch-2-101220](https://user-images.githubusercontent.com/72838874/95926245-ab843a80-0d70-11eb-99ec-d2eaeed4b1d4.jpg)
![Fluent-Form-glitch-3-101220](https://user-images.githubusercontent.com/72838874/95926247-ab843a80-0d70-11eb-9d0f-749a4ecdce35.jpg)

**Comment by alex-authlab** [comment]
Hello  @morgancarrie ,

Looks like you have changed the form, if you still need help we can help you to debug the issue. I will need the exported form file as a JSON zip, you can also create a support ticket here  [https://wpmanageninja.com/ticket/](https://wpmanageninja.com/ticket/) with the form file attached. 
I noticed you are using an optimizer cache plugin, you should check again by temporarily deactivating the optimizer plugin. That might resolve the issue.

Thanks

**Comment by morgancarrie** [comment]
Yeah, no response led to troubleshooting and a rebuild, since this was last year - but thanks!
