### ISSUE TITLE
Form locks up on creation 

### ISSUE THREAD

**Issue by Yelto1966** [fluentform/fluentform#5]
I have added the Fluentform and NinjaTables to my live site.. NinjaTables works great but Fluentform locks up will not create a form... Says Sorry an error occurred try again...

**Comment by techjewel** [comment]
Hello @Yelto1966 ,
Would you please give me some more information like screenshot or error message etc.

Thanks

**Comment by Yelto1966** [comment]
Hi As requested more Info 
![!](https://user-images.githubusercontent.com/48673358/54678271-a0b5e500-4afc-11e9-9ab2-6fb695169823.jpeg)

**Comment by Yelto1966** [comment]
It just site at that until I close it then when reopened it says "Sorry error has occurred please try again"

**Comment by techjewel** [comment]
hello @Yelto1966,
Would you please email me at support[at]wpmanageninja.com 
I am not sure what issue it has maybe some database issue. If it's on your staging site then I can wp-login and check and resolve the issue

Thanks

**Comment by Yelto1966** [comment]
Sent Details

**Comment by techjewel** [comment]
Issue resolved via email
