### ISSUE TITLE
Add filter to disable Submit component styles

### ISSUE THREAD

**Issue by seothemes** [fluentform/fluentform#50]
Currently there is no way to remove the button styles with a simple code snippet.

It can be done by clearing all of the color settings, but this is tedious.

Please see https://optimizewp.com/how-to-remove-fluent-forms-default-css-styling/

**Comment by black-eye** [comment]
Yes please! If somebody from the dev team reads this, please do something about it!

**Comment by nkb-bd** [comment]
Sorry for the late reply, A filter has been added in dev branch apply_filters('fluentform_submit_button_force_no_style', false), you will get it from the next version.
Thanks
