### ISSUE TITLE
Calendar not fit on mobile

### ISSUE THREAD

**Issue by erasys8293** [fluentform/fluentform#53]
hello sir
Calendar not fit on mobile, the scale over on mobile cant select sunday or previous month[
![437502](https://user-images.githubusercontent.com/20966499/101170364-ef106c00-3670-11eb-946b-ece5f6dbc4ad.jpg)

**Comment by alex-authlab** [comment]
Hello @erasys8293 ,
You can enable mobile support by simply adding the following line to the date input config, see [screenshot](https://prnt.sc/10gpglc) , which will resolve the issue.
```js
{
    disableMobile: "false"
}
```
Thanks
