### ISSUE TITLE
Payment Button is not added. Add Button script inside 'form' tag.

### ISSUE THREAD

**Issue by codeskventure** [fluentform/fluentform#57]
Payment Button is not added. Add Button script inside 'form' tag. i am facing frequently in my website https://codeskventure.com/seva-sindhu-application/

**Comment by alex-authlab** [comment]
Hello @codeskventure ,
I could not find any fluent form in this link ,can you please check again and also describe the issue a little more.
Thanks

**Comment by alex-authlab** [comment]
Closing the issue due to inactivity
