### ISSUE TITLE
WP Fluent From - Google Sheet integration duplicated entry

### ISSUE THREAD

**Issue by SnoozeProgrammer** [fluentform/fluentform#58]
I am using your WP Fluent Form.

Your google sheet integration works... but only when you integrate exactly 1 sheet.

When you integrate 2 or more sheets, the google sheet entry will be duplicated.

Please see the picture attached to this ticket.

Did your code forgot to clear object for each iteration?

Please help us.

<img width="2520" alt="google form integration bug" src="https://user-images.githubusercontent.com/77958768/105678456-c34a8d80-5f1f-11eb-970b-ba19d3ce3698.png">

**Comment by alex-authlab** [comment]
Hello @SnoozeProgrammer ,

Actually, as you have created two separate integration so data is being pushed separately two times and that is what shows in the activity log. The form is the same but it is two separate integration results, so you can see if any of them fail. If these were merged into one, it would not be possible to determine both integration statuses.

Thanks
