### ISSUE TITLE
WP Fluent form - Cannot click upload the image to the form via Line app in android.

### ISSUE THREAD

**Issue by TawanT** [fluentform/fluentform#60]
Cannot upload the image to the form via Line app in android.
When I click on the grey button to upload the picture. it not working.

**Comment by alex-authlab** [comment]
Hello @TawanT ,
It seems our support engineer has already replied about this issue [here](https://support.wpmanageninja.com/#/tickets/18559/view), use a browser like Chrome or firefox it should work, still if you face any issue feel free to let us know.
Thanks

**Comment by TawanT** [comment]
Thank you for your always support :)

Tawan
