### ISSUE TITLE
Could not upload CSV File on FluentCRM

### ISSUE THREAD

**Issue by nisiah78** [fluentform/fluentform#64]
![image](https://user-images.githubusercontent.com/45653625/109269442-8b37b280-781d-11eb-93ce-96f2fef42f93.png)
We try to upload a csv file even using sample file behind from the downloadable sample,  it always says mime type invalid in the API with the status 422 and error file type must be a valide CSV (as in the pictures)

**Comment by alex-authlab** [comment]
Hello @nisiah78 ,
Can you please open a support ticket attaching your CSV file here [https://wpmanageninja.com/ticket/](https://wpmanageninja.com/ticket/), our support engineers will help you to debug the issue, also, please note this is the thread for fluentforms and here is the link [https://github.com/FluentCRM/fluent-crm/issues](https://github.com/FluentCRM/fluent-crm/issues) for fluentCrm.
Thanks
