### ISSUE TITLE
Contact Form will Not Submit

### ISSUE THREAD

**Issue by JennyLynn19** [fluentform/fluentform#7]
I am using the FluentForm plugin on my business website for both a "Contact Us" and for a Job application. Both forms work only intermittently on every browser except Safari. Once the user fills in each field and clicks "submit" it usually does nothing and the data never doesn't actually gets submitted. I have tried clearing the cache/history with each browser but this doesn't solve the issue. Is there some conflict with another plugin? What's happening? Can someone please help so I can have people reach me?

**Comment by techjewel** [comment]
Hello @JennyLynn19 
Would you please submit a support ticket at [https://wpmanageninja.com/support-tickets/](https://wpmanageninja.com/support-tickets/) 
Also, Please include the page URL so I can take a look and find the issue.

Thanks

**Comment by JennyLynn19** [comment]
I just submitted my ticket, thanks.

**Comment by techjewel** [comment]
I have replied and here is the solution for others:

Looks like the nonce verification failed for some reason. You can fix this issue by add the following php code in your theme's functions.php file:

`add_filter('fluentform_nonce_verify', '__return_false');`


Then it will work fine.

Thanks

**Comment by JennyLynn19** [comment]
Thank you. I am not a programmer so can you please direct me on where
exactly to find the php file to insert into my theme?

**Comment by JennyLynn19** [comment]
I found my theme's functions.php file and have it open. Where exactly
should I insert the php code? What line?

**Comment by techjewel** [comment]
Just insert at the end of the file.
Thanks

**Comment by JennyLynn19** [comment]
I've inserted the php code as directed. The form will only work currently
with Safari and Chrome. I will not submit when I test on Firefox and my
Android phone. This is so frustrating... Do you have a solution?
