### ISSUE TITLE
PDF Creation Error

### ISSUE THREAD

**Issue by janingo** [fluentform/fluentform#71]
Installed and activated and configured WP FluentFormPro and all regarding Plugins Addos like the PDF Extension. Since last PRO-Plugin Update the PDF creation after clicking the Link in Entry Details Dashboard is not possible anymore. Browser that worked before now bringsout the following error:

{"success":false,"data":{"message":"Nonce-\u00dcberpr\u00fcfung fehlgeschlagen, bitte versuchen Sie es erneut."}}

 I guess the Plugin PDF Addon must be updated.

Help please.
Thanks.
Ingo

**Comment by techjewel** [comment]
We will release an update shortly.

**Comment by techjewel** [comment]
Version 1.1.0 has been released for Fluent Forms PDF Addon. Will work fine now.

Thanks
