### ISSUE TITLE
DATE & TIME field

### ISSUE THREAD

**Issue by mariogerini** [fluentform/fluentform#78]
Dear all
I create a form and put the field DATE & Time, but when I publish the form somethings strange happen to this two symbols " >< "! They are very very BIG! That can I do to solve this problem?
I use BRAVE browser
FluentForm plugin
many thanks for your help
[screenshot](https://drive.google.com/file/d/1_ddoIPjvUd0j78CCrQ8-aIvFJYtN2JnX/view?usp=sharing)
Mario

**Comment by alex-authlab** [comment]
Hello @mariogerini ,
This is happening because of a conflict with another script that is loading on the same page, you can submit a support ticket here [https://wpmanageninja.com/support-tickets/](https://wpmanageninja.com/support-tickets/) , to resolve the issue.
Thanks

**Comment by mariogerini** [comment]
Ok, many thanks

   Da "alex-authlab" ***@***.***
   A "fluentform/fluentform" ***@***.***
   Cc "mariogerini" ***@***.***,"Mention" ***@***.***
   Data Wed, 17 Mar 2021 21:20:26 -0700
   Oggetto Re: [fluentform/fluentform] DATE & TIME field (#78)

   Hello @mariogerini ,
   This is happening because of a conflict with another script that is loading on the same page, you can submit a support ticket here https://wpmanageninja.com/support-tickets/ , to resolve the issue.
   Thanks
