### ISSUE TITLE
Problem With Saving Selections

### ISSUE THREAD

**Issue by Firstupcleaning** [fluentform/fluentform#81]
When choosing options in the Global Settings or Form Settings, it seems that some of the options revert to their former state after being saved and updated.

One example is when using the PDF addon, if you choose to have the PDF attachment and save this selection, after you go to another tab and return, the selection is turned off.. I notice this happens with quite a few of the tab selections. They do not stay with the choices you've made even after saving..

Help would be appreciated, thanks.

**Comment by alex-authlab** [comment]
Hello @Firstupcleaning,
Seems like it could be caching issue, we are unable to recreate the issue. For further debugging can you please open a support ticket here [https://wpmanageninja.com/ticket/](https://wpmanageninja.com/ticket/) .
Thanks

**Comment by alex-authlab** [comment]
Closing the issue due to inactivity
