### ISSUE TITLE
Translations not taken

### ISSUE THREAD

**Issue by Nelmedia** [fluentform/fluentform#9]
Hi,
I've used your fluentform.pot file to create French translation (as some messages are not translated, as well as the interface itself).

It looks like though you have added strings to the file, you don't use all of them, as the message for an invalid email address is still in English. Also, the plugin's interface is about half French and half English.

With all the time I've spent translating it, I would like the translation to fully work...

**Comment by techjewel** [comment]
Hello @Nelmedia 
Can you send me the translated file so I can take a look and add in the core and fix if there has any issue in our integration.

Thanks

**Comment by Nelmedia** [comment]
You mean the .mo and .po files? Here they are.
[FluentForm_FR.zip](https://github.com/fluentform/fluentform/files/3553787/FluentForm_FR.zip)

It's been a while since I touched it, so not sure where were all the issues... But you can see in this form (https://nelmedia.ca/demos/plugins/wpmanageninja/contact-form/) that if I enter a wrong email address, the error message is in English (though it's supposed to be translated).

Also, here (https://nelmedia.ca/demos/plugins/wpmanageninja/formulaire-en-plusieurs-etapes/) I created a mult-steps form... I used the default one with the fields in English, but since the error messages are taken from the other file and it has been translated, shouldn't the error messages be in French?

By the way, it's a different topic, but it would be important that you add a summary tag/shorcode (like Caldera does) to include a summary of the form. That would be useful as the last step of a mult-steps form to show the use what he/she has filled before clicking "Submit". That way, they could go back and correct their errors if they have some or if they change their minds...

**Comment by yankiara** [comment]
We totally need a fields values summary at the end of the multi-step form.
We should be able to use the {summary} or {field_value} syntax which is available in notification emails.

**Comment by techjewel** [comment]
Hello @yankiara 
The feature is not available yet, Would you please open a new issue here in github.

**Comment by techjewel** [comment]
@Nelmedia 
We have updated the plugin and added few features. Can You update the plugin and check if your strings are still valid or need to add few more?

We will officially pack that in our next version.

Thanks

**Comment by techjewel** [comment]
Please download the file from https://github.com/fluentform/fluentform/issues/9#issuecomment-526016062 and use that in loco translate plugin to translate and modify.
