### ISSUE TITLE
Incorrect Responses in Emails from FluentForms

### ISSUE THREAD

**Issue by DenverBrady** [fluentform/fluentform#92]
We have FluentForms on our site for a questionnaire that emails completed form responses to a team member. One of the custom questions with Radio Field options (Yes/No) is showing answers from another question with Radio Field options  (Therapy/Assessment/Both/I Don't Know) in the emails. Looking at the Entries on the site, I see the actual response (Yes/No).

**Comment by alex-authlab** [comment]
Hello @DenverBrady ,
This issue needs further debugging as we did not face such an issue, can you please open a support ticket here [https://support.wpmanageninja.com/](https://support.wpmanageninja.com/), so we can help you to resolve it.
Thanks

**Comment by DenverBrady** [comment]
Thanks, Alex. I discussed this issue with a developer who was able to fix the issue.
