### ISSUE TITLE
Redirect not working

### ISSUE THREAD

**Issue by mahyargood** [fluentform/fluentform#93]
Hi, 

Redirecting to another page or URL does not work for fluentforms. I am trying to pass data to GetGist and redirect a page, however the redirect does not pass.

**Comment by alex-authlab** [comment]
Hello @mahyargood ,
Can you share a screenshot of your form settings?
![image](https://user-images.githubusercontent.com/59053748/115217577-772a7600-a127-11eb-9a01-122efd60b321.png)

Thanks
