### ISSUE TITLE
Duplicate for PDF Feeds

### ISSUE THREAD

**Issue by beatpulseapp** [fluentform/fluentform#95]
It would be nice to have a duplicate button for PDF Feeds

**Comment by alex-authlab** [comment]
Thanks for the suggestion, I will add this to internal backlog as a feature request. Please note that you can also add feature request here [https://trello.com/b/FaDlAD9B/public-roadmap-wp-fluent-forms](https://trello.com/b/FaDlAD9B/public-roadmap-wp-fluent-forms) , so may others also can see and vote for it.
Thanks
